In [1]:
pip install pykap

Collecting pykap
  Downloading pykap-0.2.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.13/site-packages (from pykap) (4.13.5)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (from pykap) (2.3.3)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from pykap) (2.32.5)
Requirement already satisfied: html5lib in /opt/anaconda3/lib/python3.13/site-packages (from pykap) (1.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4->pykap) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4->pykap) (4.15.0)
Requirement already satisfied: six>=1.9 in /opt/anaconda3/lib/python3.13/site-packages (from html5lib->pykap) (1.17.0)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.13/site-packages (from html5lib->pykap) (0.5.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pykap) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pykap) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pykap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas->pykap) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->pykap) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->pykap) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests->pykap) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests->pykap) (2026.1.4)
Downloading pykap-0.2.0-py3-none-any.whl (44 kB)
Installing collected packages: pykap
Successfully installed pykap-0.2.0
Note: you may need to restart the kernel to use updated packages.

In [121]:
import pandas as pd
import numpy as np

In [3]:
import pykap

In [4]:
sirketler = pykap.get_bist_companies(online=True, output_format="json")

In [5]:
print(sirketler)

[
    {
        "ticker": "A1CAP",
        "name": "A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/A1CAP",
        "city": "İSTANBUL",
        "auditor": "PKF ADAY BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a1416e696301416f37201c5f2e"
    },
    {
        "ticker": "A1YEN",
        "name": "A1 YENİLENEBİLİR ENERJİ ÜRETİM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/A1YEN",
        "city": "İSTANBUL",
        "auditor": "PKF ADAY BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c5794d3d66017a62a693be689d"
    },
    {
        "ticker": "AAGYO",
        "name": "AĞAOĞLU AVRASYA GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AAGYO",
        "city": "İSTANBUL",
        "auditor": "REFORM BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c49c81f743019d2dfb40633db8"
    },
    {
        "ticker": "ACP",
        "name": "A1 CAPİTAL YATIRIM MENKUL DEĞERLER A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ACP",
        "city": "İSTANBUL",
        "auditor": "PKF ADAY BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a1416e696301416f37201c5f2e"
    },
    {
        "ticker": "ACSEL",
        "name": "ACISELSAN ACIPAYAM SELÜLOZ SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ACSEL",
        "city": "DENİZLİ",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a2420327a4014209c55161144d"
    },
    {
        "ticker": "ADEL",
        "name": "ADEL KALEMCİLİK TİCARET VE SANAYİ A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ADEL",
        "city": "KOCAELİ",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a240e8d16e0140e8f159dc0033"
    },
    {
        "ticker": "ADESE",
        "name": "ADESE GAYRİMENKUL YATIRIM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ADESE",
        "city": "KONYA",
        "auditor": "TTK BAĞIMSIZ DENETİM VE YEMİNLİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a140f2ed720141164431b905a5"
    },
    {
        "ticker": "ADGYO",
        "name": "ADRA GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ADGYO",
        "city": "İZMİR",
        "auditor": "DENEYİM BAĞIMSIZ DENETİM VE DANIŞMANLIK A.Ş.",
        "company_id": "8acae2c586d22c53018a737800f804ae"
    },
    {
        "ticker": "ADLVY",
        "name": "ADİL VARLIK YÖNETİM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ADLVY",
        "city": "İSTANBUL",
        "auditor": "IŞIK YEMİNLİ MALİ MÜŞAVİRLİK VE BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c4998f24d80199e1a75ec6473e"
    },
    {
        "ticker": "AFB",
        "name": "AKTİF YATIRIM BANKASI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AFB",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "1DE05DAA8212073AE0530A4A622A2EBD"
    },
    {
        "ticker": "AFYON",
        "name": "AFYON ÇİMENTO SANAYİ T.A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AFYON",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a24158e42401415af83d607fd3"
    },
    {
        "ticker": "AGESA",
        "name": "AGESA HAYAT VE EMEKLİLİK A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AGESA",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a140e95bea0140edeb7a54015d"
    },
    {
        "ticker": "AGHOL",
        "name": "AG ANADOLU GRUBU HOLDİNG A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AGHOL",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a240f2ef4c014101b18dc000f7"
    },
    {
        "ticker": "AGROT",
        "name": "AGROTECH YÜKSEK TEKNOLOJİ VE YATIRIM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AGROT",
        "city": "İSTANBUL",
        "auditor": "ANALİZ BAĞIMSIZ DENETİM VE DANIŞMANLIK A.Ş.",
        "company_id": "8acae2c48b2fa259018bb9e449415e84"
    },
    {
        "ticker": "AGYO",
        "name": "ATAKULE GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AGYO",
        "city": "ANKARA",
        "auditor": "EREN BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a240f2ef4c0141164a06d8043a"
    },
    {
        "ticker": "AHGAZ",
        "name": "AHLATCI DOĞAL GAZ DAĞITIM ENERJİ VE YATIRIM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AHGAZ",
        "city": "İSTANBUL",
        "auditor": "HSY DANIŞMANLIK VE BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a14203278a0142095715f914d0"
    },
    {
        "ticker": "AHSGY",
        "name": "AHES GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AHSGY",
        "city": "İSTANBUL",
        "auditor": "RAM BAĞIMSIZ DENETİM VE DANIŞMANLIK A.Ş.",
        "company_id": "8acae2c59145e00a01915a44a01d1179"
    },
    {
        "ticker": "AKBNK",
        "name": "AKBANK T.A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKBNK",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a240e8d1830140e905edcd0006"
    },
    {
        "ticker": "AKCNS",
        "name": "AKÇANSA ÇİMENTO SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKCNS",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a140e8cfa00140e92b0c380016"
    },
    {
        "ticker": "AKCVR",
        "name": "AKADEMİ ÇEVRE ENTEGRE ATIK YÖNETİMİ ENDÜSTRİ A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKCVR",
        "city": "İSTANBUL",
        "auditor": "KAİZEN BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c4991b8c31019928545a1100fe"
    },
    {
        "ticker": "AKDFA",
        "name": "AKDENİZ FİNANS FAKTORİNG A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKDFA",
        "city": "İSTANBUL",
        "auditor": "HLB SAYGIN BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a1415f4d990141601150cc3212"
    },
    {
        "ticker": "AKENR",
        "name": "AKENERJİ ELEKTRİK ÜRETİM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKENR",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a14184e9cf01419bffce0b5a69"
    },
    {
        "ticker": "AKFGY",
        "name": "AKFEN GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKFGY",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a141733b56014183c1c6ed426e"
    },
    {
        "ticker": "AKFIS",
        "name": "AKFEN İNŞAAT TURİZM VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKFIS",
        "city": "ANKARA",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "8acae2c59145e00a0192aedf5db86688"
    },
    {
        "ticker": "AKFK",
        "name": "AK FİNANSAL KİRALAMA A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKFK",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a240e8d16e0140e8f31069003f"
    },
    {
        "ticker": "AKFYE",
        "name": "AKFEN YENİLENEBİLİR ENERJİ A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKFYE",
        "city": "ANKARA",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "8acae2c48304fe9e0186a66e7a9568ea"
    },
    {
        "ticker": "AKGRT",
        "name": "AKSİGORTA A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKGRT",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a140e95be70140ed12e1f4002c"
    },
    {
        "ticker": "AKHAN",
        "name": "AKHAN UN FABRİKASI VE TARIM ÜRÜNLERİ GIDA SANAYİ TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKHAN",
        "city": "ADANA",
        "auditor": "EREN BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c49b85f8ce019beef9720d5cc5"
    },
    {
        "ticker": "AKM",
        "name": "AK YATIRIM MENKUL DEĞERLER A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKM",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a240e8d16e0140e8f3d0fe0047"
    },
    {
        "ticker": "AKMEN",
        "name": "AK YATIRIM MENKUL DEĞERLER A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKMEN",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a240e8d16e0140e8f3d0fe0047"
    },
    {
        "ticker": "AKMGY",
        "name": "AKMERKEZ GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKMGY",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a240e95dc30140ecc218b30032"
    },
    {
        "ticker": "AKSA",
        "name": "AKSA AKRİLİK KİMYA SANAYİİ A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKSA",
        "city": "YALOVA",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a240f2ef470141175e189f0453"
    },
    {
        "ticker": "AKSEN",
        "name": "AKSA ENERJİ ÜRETİM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKSEN",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a241733d42014179341a147ddb"
    },
    {
        "ticker": "AKSFA",
        "name": "AK FAKTORİNG A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKSFA",
        "city": "İSTANBUL",
        "auditor": "ARTI DEĞER ULUSLARARASI BAĞIMSIZ DENETİM VE YMM A.Ş.",
        "company_id": "4028e4a240e8d16e0140e8f24bd3003b"
    },
    {
        "ticker": "AKSGY",
        "name": "AKİŞ GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKSGY",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a14158e41f01415a865c0e4d13"
    },
    {
        "ticker": "AKSUE",
        "name": "AKSU ENERJİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKSUE",
        "city": "ISPARTA",
        "auditor": "GÜÇBİR BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a140f2ed7201413a20480e0851"
    },
    {
        "ticker": "AKTIF",
        "name": "AKTİF YATIRIM BANKASI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKTIF",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "1DE05DAA8212073AE0530A4A622A2EBD"
    },
    {
        "ticker": "AKTVK",
        "name": "AKTİF BANK SUKUK VARLIK KİRALAMA A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKTVK",
        "city": "İSTANBUL",
        "auditor": "DENEYİM BAĞIMSIZ DENETİM VE DANIŞMANLIK A.Ş.",
        "company_id": "4028e4a14371e097014371f9653d00c2"
    },
    {
        "ticker": "AKYHO",
        "name": "AKDENİZ YATIRIM HOLDİNG A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/AKYHO",
        "city": "İSTANBUL",
        "auditor": "NOTE OFFİCE ULUSLARARASI BAĞIMSIZ DENETİM DANIŞMANLIK A.Ş.",
        "company_id": "4028e4a1415f4d9901416dc64bd161cb"
    },
    {
        "ticker": "ALARK",
        "name": "ALARKO HOLDİNG A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALARK",
        "city": "İSTANBUL",
        "auditor": "KPMG BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a241462fd80141500c738e36be"
    },
    {
        "ticker": "ALBRK",
        "name": "ALBARAKA TÜRK KATILIM BANKASI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALBRK",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a240f2ef4c014106a1c5ef016d"
    },
    {
        "ticker": "ALBTN",
        "name": "ALBAYRAK HAZIR BETON SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALBTN",
        "city": "İSTANBUL",
        "auditor": "ARSEN BAĞIMSIZ DENETİM HİZMETLERİ A.Ş.",
        "company_id": "8acae2c49f52d9d8019f6edc29f30cc2"
    },
    {
        "ticker": "ALCAR",
        "name": "ALARKO CARRIER SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALCAR",
        "city": "İSTANBUL",
        "auditor": "KPMG BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a241558bd9014155e085e305fd"
    },
    {
        "ticker": "ALCTL",
        "name": "ALCATEL LUCENT TELETAŞ TELEKOMÜNİKASYON A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALCTL",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a140f2ed71014110e38acb01b5"
    },
    {
        "ticker": "ALFAS",
        "name": "ALFA SOLAR ENERJİ SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALFAS",
        "city": "ANKARA",
        "auditor": "REFORM BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c5830502c30183559e2336223e"
    },
    {
        "ticker": "ALGYO",
        "name": "ALARKO GAYRİMENKUL YATIRIM ORTAKLIĞI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALGYO",
        "city": "İSTANBUL",
        "auditor": "KPMG BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a241462fd801415005df1c3612"
    },
    {
        "ticker": "ALJF",
        "name": "ALJ FİNANSMAN A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALJF",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a2422d9a6e01427b2bed8d5347"
    },
    {
        "ticker": "ALK",
        "name": "ALBARAKA TÜRK KATILIM BANKASI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALK",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a240f2ef4c014106a1c5ef016d"
    },
    {
        "ticker": "ALKA",
        "name": "ALKİM KAĞIT SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALKA",
        "city": "İZMİR",
        "auditor": "RSM TURKEY ULUSLARARASI BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a2416e697d01416f39965a5eb5"
    },
    {
        "ticker": "ALKIM",
        "name": "ALKİM ALKALİ KİMYA A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALKIM",
        "city": "İSTANBUL",
        "auditor": "RSM TURKEY ULUSLARARASI BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a140e95be70140ed147846003c"
    },
    {
        "ticker": "ALKLC",
        "name": "ALTINKILIÇ GIDA VE SÜT SANAYİ TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALKLC",
        "city": "İSTANBUL",
        "auditor": "EREN BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c48c3efac0018fabe7ce965048"
    },
    {
        "ticker": "ALNUS",
        "name": "ALNUS YATIRIM MENKUL DEĞERLER A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALNUS",
        "city": "İSTANBUL",
        "auditor": "ANY PARTNERS BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a141da49e50141e085b2112b8a"
    },
    {
        "ticker": "ALTNY",
        "name": "ALTINAY SAVUNMA TEKNOLOJİLERİ A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALTNY",
        "city": "İSTANBUL",
        "auditor": "EREN BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "8acae2c58b2fa64e018f3d2d712476e2"
    },
    {
        "ticker": "ALVES",
        "name": "ALVES KABLO SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ALVES",
        "city": "ANKARA",
        "auditor": "NOTE OFFİCE ULUSLARARASI BAĞIMSIZ DENETİM DANIŞMANLIK A.Ş.",
        "company_id": "8acae2c58b2fa64e018dc0263b1377aa"
    },
    {
        "ticker": "ANC",
        "name": "ALNUS YATIRIM MENKUL DEĞERLER A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ANC",
        "city": "İSTANBUL",
        "auditor": "ANY PARTNERS BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a141da49e50141e085b2112b8a"
    },
    {
        "ticker": "ANELE",
        "name": "ANEL ELEKTRİK PROJE TAAHHÜT VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ANELE",
        "city": "İSTANBUL",
        "auditor": "CNS BAĞIMSIZ DENETİM A.Ş.",
        "company_id": "4028e4a1416e696301416ecd11a12b86"
    },
    {
        "ticker": "ANHYT",
        "name": "ANADOLU HAYAT EMEKLİLİK A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ANHYT",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a140e95be70140ed40cb930098"
    },
    {
        "ticker": "ANSGR",
        "name": "ANADOLU ANONİM TÜRK SİGORTA ŞİRKETİ",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ANSGR",
        "city": "İSTANBUL",
        "auditor": "PwC BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş",
        "company_id": "4028e4a140e95bea0140ed21b5c10078"
    },
    {
        "ticker": "ARASE",
        "name": "DOĞU ARAS ENERJİ YATIRIMLARI A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ARASE",
        "city": "ERZURUM",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "8acae2c47afb298b017ccb97632144e5"
    },
    {
        "ticker": "ARCLK",
        "name": "ARÇELİK A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ARCLK",
        "city": "İSTANBUL",
        "auditor": "GÜNEY BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a240e95dc90140ed55b43900cf"
    },
    {
        "ticker": "ARDYZ",
        "name": "ARD GRUP BİLİŞİM TEKNOLOJİLERİ A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ARDYZ",
        "city": "ANKARA",
        "auditor": "KARAR BAĞIMSIZ DENETİM VE DANIŞMANLIK A.Ş.",
        "company_id": "8acae2c46d7599a6016dde9d93aa2b52"
    },
    {
        "ticker": "ARENA",
        "name": "ARENA BİLGİSAYAR SANAYİ VE TİCARET A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ARENA",
        "city": "İSTANBUL",
        "auditor": "DRT BAĞIMSIZ DENETİM VE SERBEST MUHASEBECİ MALİ MÜŞAVİRLİK A.Ş.",
        "company_id": "4028e4a140e95bea0140ed5af3a000da"
    },
    {
        "ticker": "ARFYE",
        "name": "ARF BİO YENİLENEBİLİR ENERJİ ÜRETİM A.Ş.",
        "summary_page": "https://www.kap.org.tr/tr/sirket/ARFYE",
        "city": "ANKARA",
        "auditor": "TİTANYUM BAĞIMSIZ DENETİM HİZMETLERİ A.Ş.",

In [6]:
comp = pykap.BISTCompany("ASELS")

In [7]:
fin = comp.get_financial_reports()

In [8]:
type(fin)

dict

In [9]:
fin.keys()

dict_keys(['20266Aylık', '20263Aylık', '2025Yıllık', '20259Aylık'])

In [12]:
fin["2025Yıllık"]

{'year': 2025, 'term': 'Yıllık', 'disc_ind': 1561039, 'results': None}

In [13]:
info = pykap.get_general_info(tick='ASELS')

In [14]:
print(info)

{'ticker': 'ASELS', 'name': 'ASELSAN ELEKTRONİK SANAYİ VE TİCARET A.Ş.', 'summary_page': 'https://www.kap.org.tr/tr/sirket/ASELS', 'city': 'ANKARA', 'auditor': 'KARAR BAĞIMSIZ DENETİM VE DANIŞMANLIK A.Ş.', 'company_id': '4028e4a1413b7ef401413bc2251e0047'}

In [15]:
report = fin["2025Yıllık"]

In [16]:
print(report["disc_ind"])

1561039

In [17]:
print(report["results"])

None

In [18]:
dir(comp)

['VALID_DISCLOSURE_TYPES',
 '_BISTCompany__announcement_no',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_announcement',
 '_save_operating_report_file',
 'auditor',
 'city',
 'company_id',
 'financial_reports',
 'get_disclosures',
 'get_expected_disclosure_list',
 'get_financial_reports',
 'get_historical_disclosure_list',
 'name',
 'output_dir',
 'save_operating_review',
 'summary_page',
 'ticker']

In [19]:
import pandas as pd

In [20]:
url = "https://www.kap.org.tr/tr/Bildirim/1561039"

tables = pd.read_html(url)

print("Bulunan tablo sayısı:", len(tables))

Bulunan tablo sayısı: 734

In [21]:
for i, table in enumerate(tables):
    print("\nTABLE:", i)
    print(table.shape)
    print(table.head())

TABLE: 0
(1, 3)
                    Bağımsız Denetim Kuruluşu Denetim Türü Görüş Türü
0  KARAR BAĞIMSIZ DENETİM VE DANIŞMANLIK A.Ş.      Sürekli     Olumlu

TABLE: 1
(3, 3)
                                                   0   1  \
0                               Kilit Denetim Konusu NaN
1  Müşteri sözleşmelerinden hasılatın muhasebeleş... NaN
2  Hasılat, TFRS 15 Müşteri Sözleşmelerinden Hası... NaN

                                                   2
0               Konunun Denetimde Nasıl Ele Alındığı
1                                                NaN
2  Müşteri sözleşmelerinden hasılatın muhasebeleş...

TABLE: 2
(2, 3)
                                                   0   1  \
0               Aktifleştirilen Geliştirme Giderleri NaN
1  Grup tarafından, işletme bünyesinde geliştiril... NaN

                                                   2
0                                                NaN
1  Aktifleştirilen geliştirme giderleri için uygu...

TABLE: 3
(2, 2)
                         0          1
0        Sunum Para Birimi   1.000 TL
1  Finansal Tablo Niteliği  Konsolide

TABLE: 4
(595, 10)
                                                   0          1  \
0                                                NaN        NaN
1  kap-fr_StatementOfFinancialPositionBalanceShee...        NaN
2                   Finansal Durum Tablosu (Bilanço)        NaN
3                          ifrs-full_AssetsAbstract|        NaN
4                                                NaN  Varlıklar

                                  2                 3                      4  \
0                               NaN  Dipnot Referansı  Cari Dönem 31.12.2025
1  Finansal Durum Tablosu (Bilanço)               NaN                    NaN
2                               NaN               NaN                    NaN
3                         Varlıklar               NaN                    NaN
4                               NaN               NaN                    NaN

                         5    6   7   8   9
0  Önceki Dönem 31.12.2024  NaN NaN NaN NaN
1                      NaN  NaN NaN NaN NaN
2                      NaN  NaN NaN NaN NaN
3                      NaN  NaN NaN NaN NaN
4                      NaN  NaN NaN NaN NaN

TABLE: 5
(1, 4)
                                  0   1   2   3
0  Finansal Durum Tablosu (Bilanço) NaN NaN NaN

TABLE: 6
(1, 5)
    0          1   2   3   4
0 NaN  Varlıklar NaN NaN NaN

TABLE: 7
(1, 6)
    0   1                2   3   4   5
0 NaN NaN  DÖNEN VARLIKLAR NaN NaN NaN

TABLE: 8
(1, 7)
    0   1   2                          3   4   5   6
0 NaN NaN NaN  Nakit ve Nakit Benzerleri NaN NaN NaN

TABLE: 9
(1, 7)
    0   1   2                                                  3   4   5   6
0 NaN NaN NaN  Gayrimenkul Projeleri Kapsamında Açılan Nakit ... NaN NaN NaN

TABLE: 10
(1, 7)
    0   1   2                    3   4   5   6
0 NaN NaN NaN  Finansal Yatırımlar NaN NaN NaN

TABLE: 11
(1, 8)
    0   1   2   3                                   4   5   6   7
0 NaN NaN NaN NaN  Kullanımı Kısıtlı Banka Bakiyeleri NaN NaN NaN

TABLE: 12
(1, 8)
    0   1   2   3                  4   5   6   7
0 NaN NaN NaN NaN  Vadeli Mevduatlar NaN NaN NaN

TABLE: 13
(1, 8)
    0   1   2   3                                   4   5   6   7
0 NaN NaN NaN NaN  Satılmaya Hazır Finansal Varlıklar NaN NaN NaN

TABLE: 14
(1, 8)
    0   1   2   3                                                4   5   6   7
0 NaN NaN NaN NaN  Vadeye Kadar Elde Tutulacak Finansal Yatırımlar NaN NaN NaN

TABLE: 15
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla... NaN NaN

    7
0 NaN

TABLE: 16
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Alım Satım Amaçlı Elde Tutulan Finansal Varlıklar NaN

    7   8
0 NaN NaN

TABLE: 17
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla... NaN

    7   8
0 NaN NaN

TABLE: 18
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla... NaN

    7   8
0 NaN NaN

TABLE: 19
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Yatırım Riski Hayat Poliçesi Sahiplerine Ait F... NaN

    7   8
0 NaN NaN

TABLE: 20
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Diğer Kapsamlı Gelir... NaN NaN

    7
0 NaN

TABLE: 21
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Diğer Kapsamlı Gelir... NaN

    7   8
0 NaN NaN

TABLE: 22
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Özkaynağa Dayalı Finansal Araçlara Yapılan Yat... NaN

    7   8
0 NaN NaN

TABLE: 23
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  İtfa Edilmiş Maliyetiyle Ölçülen Finansal Varl... NaN NaN

    7
0 NaN

TABLE: 24
(1, 8)
    0   1   2   3                          4   5   6   7
0 NaN NaN NaN NaN  Diğer Finansal Yatırımlar NaN NaN NaN

TABLE: 25
(1, 7)
    0   1   2                                    3   4   5   6
0 NaN NaN NaN  Teminata Verilen Finansal Varlıklar NaN NaN NaN

TABLE: 26
(1, 7)
    0   1   2                 3   4   5   6
0 NaN NaN NaN  Ticari Alacaklar NaN NaN NaN

TABLE: 27
(1, 8)
    0   1   2   3                                      4   5   6   7
0 NaN NaN NaN NaN  İlişkili Taraflardan Ticari Alacaklar NaN NaN NaN

TABLE: 28
(1, 8)
    0   1   2   3                                              4   5   6   7
0 NaN NaN NaN NaN  İlişkili Olmayan Taraflardan Ticari Alacaklar NaN NaN NaN

TABLE: 29
(1, 7)
    0   1   2                                          3   4   5   6
0 NaN NaN NaN  Finans Sektörü Faaliyetlerinden Alacaklar NaN NaN NaN

TABLE: 30
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Finans Sektörü Faaliyetlerinden İlişkili Taraf... NaN NaN

    7
0 NaN

TABLE: 31
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Finans Sektörü Faaliyetlerinden İlişkili Olmay... NaN NaN

    7
0 NaN

TABLE: 32
(1, 7)
    0   1   2                                         3   4   5   6
0 NaN NaN NaN  Türkiye Cumhuriyet Merkez Bankası Hesabı NaN NaN NaN

TABLE: 33
(1, 7)
    0   1   2                3   4   5   6
0 NaN NaN NaN  Diğer Alacaklar NaN NaN NaN

TABLE: 34
(1, 8)
    0   1   2   3                                     4   5   6   7
0 NaN NaN NaN NaN  İlişkili Taraflardan Diğer Alacaklar NaN NaN NaN

TABLE: 35
(1, 8)
    0   1   2   3                                             4   5   6   7
0 NaN NaN NaN NaN  İlişkili Olmayan Taraflardan Diğer Alacaklar NaN NaN NaN

TABLE: 36
(1, 7)
    0   1   2                                         3   4   5   6
0 NaN NaN NaN  Müşteri Sözleşmelerinden Doğan Varlıklar NaN NaN NaN

TABLE: 37
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Devam Eden İnşaat ve Taahhüt İşlerinden Doğan ... NaN NaN

    7
0 NaN

TABLE: 38
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Mal ve Hizmet Satışlarından Doğan Sözleşme Var... NaN NaN

    7
0 NaN

TABLE: 39
(1, 8)
    0   1   2   3                          4   5   6   7
0 NaN NaN NaN NaN  Diğer Sözleşme Varlıkları NaN NaN NaN

TABLE: 40
(1, 7)
    0   1   2                                                  3   4   5   6
0 NaN NaN NaN  İmtiyaz Sözleşmelerine İlişkin Finansal Varlıklar NaN NaN NaN

TABLE: 41
(1, 7)
    0   1   2              3   4   5   6
0 NaN NaN NaN  Türev Araçlar NaN NaN NaN

TABLE: 42
(1, 8)
    0   1   2   3                                4   5   6   7
0 NaN NaN NaN NaN  Alım Satım Amaçlı Türev Araçlar NaN NaN NaN

TABLE: 43
(1, 8)
    0   1   2   3                                     4   5   6   7
0 NaN NaN NaN NaN  Riskten Korunma Amaçlı Türev Araçlar NaN NaN NaN

TABLE: 44
(1, 7)
    0   1   2        3   4   5   6
0 NaN NaN NaN  Stoklar NaN NaN NaN

TABLE: 45
(1, 7)
    0   1   2                        3   4   5   6
0 NaN NaN NaN  Proje Halindeki Stoklar NaN NaN NaN

TABLE: 46
(1, 7)
    0   1   2                3   4   5   6
0 NaN NaN NaN  Canlı Varlıklar NaN NaN NaN

TABLE: 47
(1, 7)
    0   1   2                       3   4   5   6
0 NaN NaN NaN  Peşin Ödenmiş Giderler NaN NaN NaN

TABLE: 48
(1, 8)
    0   1   2   3                                          4   5   6   7
0 NaN NaN NaN NaN  İlişkili Taraflara Peşin Ödenmiş Giderler NaN NaN NaN

TABLE: 49
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  İlişkili Olmayan Taraflara Peşin Ödenmiş Giderler NaN NaN

    7
0 NaN

TABLE: 50
(1, 7)
    0   1   2                                         3   4   5   6
0 NaN NaN NaN  Ertelenmiş Sigortacılık Üretim Giderleri NaN NaN NaN

TABLE: 51
(1, 7)
    0   1   2                                       3   4   5   6
0 NaN NaN NaN  Cari Dönem Vergisiyle İlgili Varlıklar NaN NaN NaN

TABLE: 52
(1, 7)
    0   1   2                                             3   4   5   6
0 NaN NaN NaN  Nakit Dışı Serbest Kullanılabilir Teminatlar NaN NaN NaN

TABLE: 53
(1, 7)
    0   1   2                      3   4   5   6
0 NaN NaN NaN  Diğer Dönen Varlıklar NaN NaN NaN

TABLE: 54
(1, 8)
    0   1   2   3                                           4   5   6   7
0 NaN NaN NaN NaN  İlişkili Taraflardan Diğer Dönen Varlıklar NaN NaN NaN

TABLE: 55
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  İlişkili Olmayan Taraflardan Diğer Dönen Varlı... NaN NaN

    7
0 NaN

TABLE: 56
(1, 7)
    0   1   2           3   4   5   6
0 NaN NaN NaN  ARA TOPLAM NaN NaN NaN

TABLE: 57
(1, 7)
    0   1   2                                             3   4   5   6
0 NaN NaN NaN  Satış Amaçlı Sınıflandırılan Duran Varlıklar NaN NaN NaN

TABLE: 58
(1, 7)
    0   1   2                                                  3   4   5   6
0 NaN NaN NaN  Ortaklara Dağıtılmak Üzere Elde Tutulan Duran ... NaN NaN NaN

TABLE: 59
(1, 7)
    0   1   2                       3   4   5   6
0 NaN NaN NaN  TOPLAM DÖNEN VARLIKLAR NaN NaN NaN

TABLE: 60
(1, 6)
    0   1                2   3   4   5
0 NaN NaN  DURAN VARLIKLAR NaN NaN NaN

TABLE: 61
(1, 7)
    0   1   2                    3   4   5   6
0 NaN NaN NaN  Finansal Yatırımlar NaN NaN NaN

TABLE: 62
(1, 8)
    0   1   2   3                                   4   5   6   7
0 NaN NaN NaN NaN  Kullanımı Kısıtlı Banka Bakiyeleri NaN NaN NaN

TABLE: 63
(1, 8)
    0   1   2   3                  4   5   6   7
0 NaN NaN NaN NaN  Vadeli Mevduatlar NaN NaN NaN

TABLE: 64
(1, 8)
    0   1   2   3                                    4   5   6   7
0 NaN NaN NaN NaN  Satılmaya Hazır Finansal Yatırımlar NaN NaN NaN

TABLE: 65
(1, 8)
    0   1   2   3                                                4   5   6   7
0 NaN NaN NaN NaN  Vadeye Kadar Elde Tutulacak Finansal Yatırımlar NaN NaN NaN

TABLE: 66
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla... NaN NaN

    7
0 NaN

TABLE: 67
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Alım Satım Amaçlı Elde Tutulan Finansal Varlıklar NaN

    7   8
0 NaN NaN

TABLE: 68
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla... NaN

    7   8
0 NaN NaN

TABLE: 69
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla... NaN

    7   8
0 NaN NaN

TABLE: 70
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Yatırım Riski Hayat Poliçesi Sahiplerine Ait F... NaN

    7   8
0 NaN NaN

TABLE: 71
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Diğer Kapsamlı Gelir... NaN NaN

    7
0 NaN

TABLE: 72
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Gerçeğe Uygun Değer Farkı Diğer Kapsamlı Gelir... NaN

    7   8
0 NaN NaN

TABLE: 73
(1, 9)
    0   1   2   3   4                                                  5   6  \
0 NaN NaN NaN NaN NaN  Özkaynağa Dayalı Finansal Araçlara Yapılan Yat... NaN

    7   8
0 NaN NaN

TABLE: 74
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  İtfa Edilmiş Maliyetiyle Ölçülen Finansal Varl... NaN NaN

    7
0 NaN

TABLE: 75
(1, 8)
    0   1   2   3                          4   5   6   7
0 NaN NaN NaN NaN  Diğer Finansal Yatırımlar NaN NaN NaN

TABLE: 76
(1, 7)
    0   1   2                                                  3   4   5   6
0 NaN NaN NaN  İştirakler, İş Ortaklıkları ve Bağlı Ortaklıkl... NaN NaN NaN

TABLE: 77
(1, 7)
    0   1   2                 3   4   5   6
0 NaN NaN NaN  Ticari Alacaklar NaN NaN NaN

TABLE: 78
(1, 8)
    0   1   2   3                                      4   5   6   7
0 NaN NaN NaN NaN  İlişkili Taraflardan Ticari Alacaklar NaN NaN NaN

TABLE: 79
(1, 8)
    0   1   2   3                                              4   5   6   7
0 NaN NaN NaN NaN  İlişkili Olmayan Taraflardan Ticari Alacaklar NaN NaN NaN

TABLE: 80
(1, 7)
    0   1   2                                          3   4   5   6
0 NaN NaN NaN  Finans Sektörü Faaliyetlerinden Alacaklar NaN NaN NaN

TABLE: 81
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Finans Sektörü Faaliyetlerinden İlişkili Taraf... NaN NaN

    7
0 NaN

TABLE: 82
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Finans Sektörü Faaliyetlerinden İlişkili Olmay... NaN NaN

    7
0 NaN

TABLE: 83
(1, 7)
    0   1   2                3   4   5   6
0 NaN NaN NaN  Diğer Alacaklar NaN NaN NaN

TABLE: 84
(1, 8)
    0   1   2   3                                     4   5   6   7
0 NaN NaN NaN NaN  İlişkili Taraflardan Diğer Alacaklar NaN NaN NaN

TABLE: 85
(1, 8)
    0   1   2   3                                             4   5   6   7
0 NaN NaN NaN NaN  İlişkili Olmayan Taraflardan Diğer Alacaklar NaN NaN NaN

TABLE: 86
(1, 7)
    0   1   2                                         3   4   5   6
0 NaN NaN NaN  Müşteri Sözleşmelerinden Doğan Varlıklar NaN NaN NaN

TABLE: 87
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Devam Eden İnşaat ve Taahhüt İşlerinden Doğan ... NaN NaN

    7
0 NaN

TABLE: 88
(1, 8)
    0   1   2   3                                                  4   5   6  \
0 NaN NaN NaN NaN  Mal ve Hizmet Satışlarından Doğan Sözleşme Var... NaN NaN

    7
0 NaN

TABLE: 89
(1, 8)
    0   1   2   3                          4   5   6   7
0 NaN NaN NaN NaN  Diğer Sözleşme Varlıkları NaN NaN NaN

TABLE: 90
(1, 7)
    0   1   2                                                  3   4   5   6
0 NaN NaN NaN  İmtiyaz Sözleşmelerine İlişkin Finansal Varlıklar NaN NaN NaN

TABLE: 91
(1, 7)
    0   1   2              3   4   5   6
0 NaN NaN NaN  Türev Araçlar NaN NaN NaN

TABLE: 92
(1, 8)
    0   1   2   3                                4   5   6   7
0 NaN NaN NaN NaN  Alım Satım Amaçlı Türev Araçlar NaN NaN NaN

TABLE: 93
(1, 8)
    0   1   2   3                                     4   5   6   7
0 NaN NaN NaN NaN  Riskten Korunma Amaçlı Türev Araçlar NaN NaN NaN

TABLE: 94
(1, 7)
    0   1   2        3   4   5   6
0 NaN NaN NaN  Stoklar NaN NaN NaN

TABLE: 95
(1, 7)
    0   1   2                                          3   4   5   6
0 NaN NaN NaN  Özkaynak Yöntemiyle Değerlenen Yatırımlar NaN NaN NaN

TABLE: 96
(1, 7)
    0   1   2                3   4   5   6
0 NaN NaN NaN  Canlı Varlıklar NaN NaN NaN

TABLE: 97
(1, 7)
    0   1   2                              3   4   5   6
0 NaN NaN NaN  Yatırım Amaçlı Gayrimenkuller NaN NaN NaN

TABLE: 98
(1, 7)
    0   1   2                                              3   4   5   6
0 NaN NaN NaN  Proje Halindeki Yatırım Amaçlı Gayrimenkuller NaN NaN NaN

TABLE: 99
(1, 7)
    0   1   2                      3   4   5   6
0 NaN NaN NaN  Maddi Duran Varlıklar NaN NaN NaN

TABLE: 100
(1, 8)
    0   1   2   3                 4   5   6   7
0 NaN NaN NaN NaN  Arazi ve Arsalar NaN NaN NaN

TABLE: 101
(1, 8)
    0   1   2   3                                 4   5   6   7
0 NaN NaN NaN NaN  Yeraltı ve Yerüstü Düzenlemeleri NaN NaN NaN

TABLE: 102
(1, 8)
    0   1   2   3        4   5   6   7
0 NaN NaN NaN NaN  Binalar NaN NaN NaN

TABLE: 103
(1, 8)
    0   1   2   3                          4   5   6   7
0 NaN NaN NaN NaN  Tesis, Makine ve Cihazlar NaN NaN NaN

TABLE: 104
(1, 8)
    0   1   2   3         4   5   6   7
0 NaN NaN NaN NaN  Taşıtlar NaN NaN NaN

TABLE: 105
(1, 8)
    0   1   2   3                       4   5   6   7
0 NaN NaN NaN NaN  Mobilya ve Demirbaşlar NaN NaN NaN

TABLE: 106
(1, 8)
    0   1   2   3                4   5   6   7
0 NaN NaN NaN NaN  Özel Maliyetler NaN NaN NaN

TABLE: 107
(1, 8)
    0   1   2   3                  4   5   6   7
0 NaN NaN NaN NaN  Taşıyıcı Bitkiler NaN NaN NaN

TABLE: 108
(1, 8)
    0   1   2   3                              4   5   6   7
0 NaN NaN NaN NaN  Özel Tükenmeye Tabi Varlıklar NaN NaN NaN

TABLE: 109
(1, 8)
    0   1   2   3                           4   5   6   7
0 NaN NaN NaN NaN  Yapılmakta Olan Yatırımlar NaN NaN NaN

TABLE: 110
(1, 8)
    0   1   2   3                                     4   5   6   7
0 NaN NaN NaN NaN  Faaliyet Kiralamasına Konu Varlıklar NaN NaN NaN

TABLE: 111
(1, 8)
    0   1   2   3                            4   5   6   7
0 NaN NaN NaN NaN  Diğer Maddi Duran Varlıklar NaN NaN NaN

TABLE: 112
(1, 7)
    0   1   2                          3   4   5   6
0 NaN NaN NaN  Kullanım Hakkı Varlıkları NaN NaN NaN

TABLE: 113
(1, 7)
    0   1   2                              3   4   5   6
0 NaN NaN NaN  Maddi Olmayan Duran Varlıklar NaN NaN NaN

TABLE: 114
(1, 8)
    0   1   2   3         4   5   6   7
0 NaN NaN NaN NaN  Şerefiye NaN NaN NaN

TABLE: 115
(1, 8)
    0   1   2   3                                      4   5   6   7
0 NaN NaN NaN NaN  İmtiyaz Sözleşmelerinden Doğan Haklar NaN NaN NaN

TABLE: 116
(1, 8)
    0   1   2   3             4   5   6   7
0 NaN NaN NaN NaN  Diğer Haklar NaN NaN NaN

TABLE: 117
(1, 8)
    0   1   2   3          4   5   6   7
0 NaN NaN NaN NaN  Patentler NaN NaN NaN

TABLE: 118
(1, 8)
    0   1   2   3         4   5   6   7
0 NaN NaN NaN NaN  Markalar NaN NaN NaN

TABLE: 119
(1, 8)
    0   1   2   3          4   5   6   7
0 NaN NaN NaN NaN  Lisanslar NaN NaN NaN

TABLE: 120
(1, 8)
    0   1   2   3                       4   5   6   7
0 NaN NaN NaN NaN  Bilgisayar Yazılımları NaN NaN NaN

TABLE: 121
(1, 8)
    0   1   2   3                                       4   5   6   7
0 NaN NaN NaN NaN  Aktifleştirilen Geliştirme Maliyetleri NaN NaN NaN

TABLE: 122
(1, 8)
    0   1   2   3                                    4   5   6   7
0 NaN NaN NaN NaN  Diğer Maddi Olmayan Duran Varlıklar NaN NaN NaN

TABLE: 123
(1, 7)
    0   1   2                       3   4   5   6
0 NaN NaN NaN  Peşin Ödenmiş Giderler NaN NaN NaN

TABLE: 124
(1, 8)
    0   1   2   3                                          4   5   6   7
0 NaN NaN NaN NaN  İlişkili Taraflara Peşin Ödenmiş Giderler NaN NaN NaN

TABLE: 125
(1, 8)

In [22]:
df = tables[4]

print(df.shape)
print(df.columns)

(595, 10)
Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [23]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

df.head(30)

,0,1,2,3,4,5,6,7,8,9
0,NaN,NaN,NaN,Dipnot Referansı,Cari Dönem 31.12.2025,Önceki Dönem 31.12.2024,NaN,NaN,NaN,NaN
1,kap-fr_StatementOfFinancialPositionBalanceShee...,NaN,Finansal Durum Tablosu (Bilanço),NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Finansal Durum Tablosu (Bilanço),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ifrs-full_AssetsAbstract|,NaN,Varlıklar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Varlıklar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ifrs-full_CurrentAssetsAbstract|http://www.mkk...,NaN,DÖNEN VARLIKLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,DÖNEN VARLIKLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ifrs-full_CashAndCashEquivalents|,NaN,Nakit ve Nakit Benzerleri,3,29.086.476,21.776.847,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,Nakit ve Nakit Benzerleri,NaN,NaN,NaN,NaN,NaN,NaN
9,kap-fr_CashAccountsRegardingRealEstateProjects|,NaN,Gayrimenkul Projeleri Kapsamında Açılan Nakit ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,Gayrimenkul Projeleri Kapsamında Açılan Nakit ...,NaN,NaN,NaN,NaN,NaN,NaN
11,kap-fr_CurrentFinancialInvestments|http://www....,NaN,Finansal Yatırımlar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,Finansal Yatırımlar,NaN,NaN,NaN,NaN,NaN,NaN
13,kap-fr_RestrictedCurrentBankBalances|http://ww...,NaN,Kullanımı Kısıtlı Banka Bakiyeleri,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,Kullanımı Kısıtlı Banka Bakiyeleri,NaN,NaN,NaN,NaN,NaN
15,kap-fr_TimeDepositsClassifiedAsCurrent|http://...,NaN,Vadeli Mevduatlar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,Vadeli Mevduatlar,NaN,NaN,NaN,NaN,NaN
17,ifrs-full_CurrentFinancialAssetsAvailableforsa...,NaN,Satılmaya Hazır Finansal Varlıklar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,Satılmaya Hazır Finansal Varlıklar,NaN,NaN,NaN,NaN,NaN
19,kap-fr_CurrentFinancialInvestmentsHeldToMaturi...,NaN,Vadeye Kadar Elde Tutulacak Finansal Yatırımlar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,Vadeye Kadar Elde Tutulacak Finansal Yatırımlar,NaN,NaN,NaN,NaN,NaN
21,ifrs-full_CurrentFinancialAssetsAtFairValueThr...,NaN,Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla...,NaN,NaN,NaN,NaN,NaN
23,kap-fr_CurrentFinancialAssetsHeldForTrading|ht...,NaN,Alım Satım Amaçlı Elde Tutulan Finansal Varlıklar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,Alım Satım Amaçlı Elde Tutulan Finansal Varlıklar,NaN,NaN,NaN,NaN
25,kap-fr_OtherCurrentFinancialAssetsMeasuredAtFa...,NaN,Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla...,NaN,NaN,NaN,NaN
27,kap-fr_CurrentFinancialAssetsDesignatedAsAtFai...,NaN,Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtıla...,NaN,NaN,NaN,NaN
29,kap-fr_FinancialInvestmentsWithRisksOnPolicyho...,NaN,Yatırım Riski Hayat Poliçesi Sahiplerine Ait F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df[df.astype(str).apply(
    lambda row: row.str.contains(
        "TOPLAM VARLIKLAR|HASILAT|ÖZKAYNAKLAR|DÖNEN VARLIKLAR",
        case=False,
        regex=True
    ).any(),
    axis=1
)]

,0,1,2,3,4,5,6,7,8,9
5,ifrs-full_CurrentAssetsAbstract|http://www.mkk...,NaN,DÖNEN VARLIKLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,DÖNEN VARLIKLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,ifrs-full_OtherCurrentAssets|,NaN,Diğer Dönen Varlıklar,19,5.820.614,3.870.451,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,Diğer Dönen Varlıklar,NaN,NaN,NaN,NaN,NaN,NaN
99,kap-fr_OtherCurrentAssetsDueFromRelatedParties|,NaN,İlişkili Taraflardan Diğer Dönen Varlıklar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,İlişkili Taraflardan Diğer Dönen Varlıklar,NaN,NaN,NaN,NaN,NaN
101,kap-fr_OtherCurrentAssetsDueFromUnrelatedParties|,NaN,İlişkili Olmayan Taraflardan Diğer Dönen Varlı...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,NaN,NaN,NaN,İlişkili Olmayan Taraflardan Diğer Dönen Varlı...,NaN,NaN,NaN,NaN,NaN
109,ifrs-full_CurrentAssets|http://www.xbrl.org/20...,NaN,TOPLAM DÖNEN VARLIKLAR,NaN,174.984.061,138.901.174,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,TOPLAM DÖNEN VARLIKLAR,NaN,NaN,NaN,NaN,NaN,NaN
257,ifrs-full_Assets|http://www.xbrl.org/2003/role...,NaN,TOPLAM VARLIKLAR,NaN,431.587.329,317.802.518,NaN,NaN,NaN,NaN
258,NaN,NaN,TOPLAM VARLIKLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,ifrs-full_EquityAbstract|http://www.xbrl.org/2...,NaN,ÖZKAYNAKLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
486,NaN,NaN,ÖZKAYNAKLAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN
487,ifrs-full_EquityAttributableToOwnersOfParent|,NaN,Ana Ortaklığa Ait Özkaynaklar,NaN,250.430.356,183.640.090,NaN,NaN,NaN,NaN
488,NaN,NaN,NaN,Ana Ortaklığa Ait Özkaynaklar,NaN,NaN,NaN,NaN,NaN,NaN
591,ifrs-full_Equity|http://www.xbrl.org/2003/role...,NaN,TOPLAM ÖZKAYNAKLAR,NaN,251.786.294,185.027.818,NaN,NaN,NaN,NaN
592,NaN,NaN,NaN,TOPLAM ÖZKAYNAKLAR,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
keywords = [
    "NAKİT",
    "TİCARİ ALACAK",
    "STOKLAR",
    "KISA VADELİ YÜKÜMLÜLÜK",
    "UZUN VADELİ YÜKÜMLÜLÜK",
    "TOPLAM YÜKÜMLÜLÜK",
    "HASILAT",
    "BRÜT KAR",
    "FAALİYET KARI",
    "NET DÖNEM KARI"
]

pattern = "|".join(keywords)

result = df[
    df.astype(str).apply(
        lambda row: row.str.contains(
            pattern,
            case=False,
            regex=True
        ).any(),
        axis=1
    )
]

result

,0,1,2,3,4,5,6,7,8,9
7,ifrs-full_CashAndCashEquivalents|,NaN,Nakit ve Nakit Benzerleri,3,29.086.476,21.776.847,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,Nakit ve Nakit Benzerleri,NaN,NaN,NaN,NaN,NaN,NaN
9,kap-fr_CashAccountsRegardingRealEstateProjects|,NaN,Gayrimenkul Projeleri Kapsamında Açılan Nakit ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,Gayrimenkul Projeleri Kapsamında Açılan Nakit ...,NaN,NaN,NaN,NaN,NaN,NaN
43,ifrs-full_CurrentTradeReceivables|http://www.x...,NaN,Ticari Alacaklar,6,38.859.628,37.114.995,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,Ticari Alacaklar,NaN,NaN,NaN,NaN,NaN,NaN
45,kap-fr_CurrentTradeReceivablesDueFromRelaedPar...,NaN,İlişkili Taraflardan Ticari Alacaklar,5,32.068.651,16.550.325,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,İlişkili Taraflardan Ticari Alacaklar,NaN,NaN,NaN,NaN,NaN
47,kap-fr_CurrentTradeReceivablesDueFromUnrelated...,NaN,İlişkili Olmayan Taraflardan Ticari Alacaklar,NaN,6.790.977,20.564.670,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,İlişkili Olmayan Taraflardan Ticari Alacaklar,NaN,NaN,NaN,NaN,NaN
79,ifrs-full_Inventories|http://www.xbrl.org/2003...,NaN,Stoklar,9,73.660.730,56.901.022,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,Stoklar,NaN,NaN,NaN,NaN,NaN,NaN
81,kap-fr_CurrentInventoriesWorkInProgress|http:/...,NaN,Proje Halindeki Stoklar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,Proje Halindeki Stoklar,NaN,NaN,NaN,NaN,NaN,NaN
95,ifrs-full_CurrentNoncashAssetsPledgedAsCollate...,NaN,Nakit Dışı Serbest Kullanılabilir Teminatlar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,Nakit Dışı Serbest Kullanılabilir Teminatlar,NaN,NaN,NaN,NaN,NaN,NaN
145,ifrs-full_NoncurrentTradeReceivables|http://ww...,NaN,Ticari Alacaklar,6,87.944.574,71.963.031,NaN,NaN,NaN,NaN
146,NaN,NaN,NaN,Ticari Alacaklar,NaN,NaN,NaN,NaN,NaN,NaN
147,kap-fr_NoncurrentTradeReceivablesDueFromRelate...,NaN,İlişkili Taraflardan Ticari Alacaklar,5,42.805.303,52.540.861,NaN,NaN,NaN,NaN
148,NaN,NaN,NaN,NaN,İlişkili Taraflardan Ticari Alacaklar,NaN,NaN,NaN,NaN,NaN
149,kap-fr_NoncurrentTradeReceivablesDueFromUnrela...,NaN,İlişkili Olmayan Taraflardan Ticari Alacaklar,NaN,45.139.271,19.422.170,NaN,NaN,NaN,NaN
150,NaN,NaN,NaN,NaN,İlişkili Olmayan Taraflardan Ticari Alacaklar,NaN,NaN,NaN,NaN,NaN
179,ifrs-full_NoncurrentInventories|http://www.xbr...,NaN,Stoklar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,NaN,NaN,NaN,Stoklar,NaN,NaN,NaN,NaN,NaN,NaN
247,ifrs-full_NoncurrentNoncashAssetsPledgedAsColl...,NaN,Nakit Dışı Serbest Kullanılabilir Teminatlar,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,NaN,NaN,NaN,Nakit Dışı Serbest Kullanılabilir Teminatlar,NaN,NaN,NaN,NaN,NaN,NaN
261,ifrs-full_CurrentLiabilitiesAbstract|http://ww...,NaN,KISA VADELİ YÜKÜMLÜLÜKLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,NaN,NaN,KISA VADELİ YÜKÜMLÜLÜKLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,ifrs-full_OtherCurrentNonfinancialLiabilities|...,NaN,Diğer Kısa Vadeli Yükümlülükler,19,117.447,45.758,NaN,NaN,NaN,NaN
370,NaN,NaN,NaN,Diğer Kısa Vadeli Yükümlülükler,NaN,NaN,NaN,NaN,NaN,NaN
371,kap-fr_OtherCurrentNonfinancialLiabilitiesToRe...,NaN,İlişkili Taraflara Diğer Kısa Vadeli Yükümlülü...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372,NaN,NaN,NaN,NaN,İlişkili Taraflara Diğer Kısa Vadeli Yükümlülü...,NaN,NaN,NaN,NaN,NaN
373,kap-fr_OtherCurrentNonfinancialLiabilitiesToUn...,NaN,İlişkili Olmayan Taraflara Diğer Kısa Vadeli Y...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,NaN,NaN,NaN,NaN,İlişkili Olmayan Taraflara Diğer Kısa Vadeli Y...,NaN,NaN,NaN,NaN,NaN
381,ifrs-full_CurrentLiabilities|http://www.xbrl.o...,NaN,TOPLAM KISA VADELİ YÜKÜMLÜLÜKLER,NaN,126.229.330,91.312.082,NaN,NaN,NaN,NaN
382,NaN,NaN,NaN,TOPLAM KISA VADELİ YÜKÜMLÜLÜKLER,NaN,NaN,NaN,NaN,NaN,NaN
383,ifrs-full_NoncurrentLiabilitiesAbstract|http:/...,NaN,UZUN VADELİ YÜKÜMLÜLÜKLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
384,NaN,NaN,UZUN VADELİ YÜKÜMLÜLÜKLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
475,ifrs-full_OtherNoncurrentNonfinancialLiabiliti...,NaN,Diğer Uzun Vadeli Yükümlülükler,19,215.889,52.591,NaN,NaN,NaN,NaN
476,NaN,NaN,NaN,Diğer Uzun Vadeli Yükümlülükler,NaN,NaN,NaN,NaN,NaN,NaN
477,kap-fr_OtherNoncurrentNonfinancialLiabilitiesT...,NaN,İlişkili Taraflara Diğer Uzun Vadeli Yükümlülü...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
478,NaN,NaN,NaN,NaN,İlişkili Taraflara Diğer Uzun Vadeli Yükümlülü...,NaN,NaN,NaN,NaN,NaN
479,kap-fr_OtherNoncurrentNonfinancialLiabilitiesT...,NaN,İlişkili Olmayan Taraflara Diğer Uzun Vadeli Y...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,NaN,NaN,NaN,NaN,İlişkili Olmayan Taraflara Diğer Uzun Vadeli Y...,NaN,NaN,NaN,NaN,NaN
481,ifrs-full_NoncurrentLiabilities|http://www.xbr...,NaN,TOPLAM UZUN VADELİ YÜKÜMLÜLÜKLER,NaN,53.571.705,41.462.618,NaN,NaN,NaN,NaN
482,NaN,NaN,NaN,TOPLAM UZUN VADELİ YÜKÜMLÜLÜKLER,NaN,NaN,NaN,NaN,NaN,NaN
483,ifrs-full_Liabilities|http://www.xbrl.org/2003...,NaN,TOPLAM YÜKÜMLÜLÜKLER,NaN,179.801.035,132.774.700,NaN,NaN,NaN,NaN
484,NaN,NaN,TOPLAM YÜKÜMLÜLÜKLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
543,kap-fr_AccumulatedGainsOrLossesOnCashFlowHedge...,NaN,Nakit Akış Riskinden Korunma Kazançları (Kayıp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
544,NaN,NaN,NaN,NaN,NaN,NaN,Nakit Akış Riskinden Korunma Kazançları (Kayıp...,NaN,NaN,NaN
587,kap-fr_CurrentPeriodNetProfitOrLossClassifiedI...,NaN,Net Dönem Karı veya Zararı,NaN,29.949.517,20.024.831,NaN,NaN,NaN,NaN
588,NaN,NaN,NaN,NaN,Net Dönem Karı veya Zararı,NaN,NaN,NaN,NaN,NaN

In [ ]:
xbrl_code = "ifrs-full_CashAndCashEquivalents"

row = df[
    df[0].astype(str).str.startswith(xbrl_code)
]

row

,0,1,2,3,4,5,6,7,8,9
7,ifrs-full_CashAndCashEquivalents|,NaN,Nakit ve Nakit Benzerleri,3,29.086.476,21.776.847,NaN,NaN,NaN,NaN

In [95]:
selected_fin = "ifrs-full_CashAndCashEquivalents"

In [146]:
def get_financial_item(df, selected_fin):

    mask = df[0].astype(str).str.startswith(selected_fin + "|")
    selected_row = df[mask]

    if selected_row.empty:
        return np.nan

    value = selected_row[4].iloc[0]

    return value

In [147]:
value = get_financial_item(df, selected_fin)

In [148]:
def parse_financial_value(value):
    if pd.isna(value):
        return np.nan

    if value.startswith("(") and value.endswith(")"):
        value = value[1:-1]
        value = value.replace(".", "")
        sayı = int(value)
        sonuc = sayı * -1
    else:
        sonuc = int(value.replace(".", ""))

    return sonuc

In [149]:
financial_items = {
    "CASH": "ifrs-full_CashAndCashEquivalents",
    "RECEIVABLES": "ifrs-full_CurrentTradeReceivables",
    "INVENTORY": "ifrs-full_Inventories",
    "CURRENT_ASSETS": "ifrs-full_CurrentAssets",
    "TOTAL_ASSETS": "ifrs-full_Assets",
    "CURRENT_LIABILITIES": "ifrs-full_CurrentLiabilities",
    "TOTAL_LIABILITIES": "ifrs-full_Liabilities"
}

In [150]:
financial_data = {}

for name, xbrl_code in financial_items.items():

    raw_value = get_financial_item(df, xbrl_code)
    value = parse_financial_value(raw_value)

    financial_data[name] = value

print(financial_data)

{'CASH': 29086476, 'RECEIVABLES': 38859628, 'INVENTORY': 73660730, 'CURRENT_ASSETS': 174984061, 'TOTAL_ASSETS': 431587329, 'CURRENT_LIABILITIES': 126229330, 'TOTAL_LIABILITIES': 179801035}

In [131]:
financial_items.items()

dict_items([('CASH', 'ifrs-full_CashAndCashEquivalents'), ('RECEIVABLES', 'ifrs-full_CurrentTradeReceivables'), ('INVENTORY', 'ifrs-full_Inventories'), ('CURRENT_ASSETS', 'ifrs-full_CurrentAssets'), ('TOTAL_ASSETS', 'ifrs-full_Assets'), ('CURRENT_LIABILITIES', 'ifrs-full_CurrentLiabilities'), ('TOTAL_LIABILITIES', 'ifrs-full_Liabilities')])

In [132]:
get_financial_item(df, xbrl_code)

'29.086.476'

In [153]:
for key, report in fin.items():

    if report["term"] == "Yıllık":

        year = report["year"]
        disc_ind = report["disc_ind"]

        url = f"https://www.kap.org.tr/tr/Bildirim/{disc_ind}"

        print(year, url)

2025 https://www.kap.org.tr/tr/Bildirim/1561039

In [154]:
for key, report in fin.items():

    if report["term"] == "Yıllık":

        year = report["year"]
        disc_ind = report["disc_ind"]

        url = f"https://www.kap.org.tr/tr/Bildirim/{disc_ind}"

        tables = pd.read_html(url)
        df = tables[4]

        financial_data = {}

        for name, xbrl_code in financial_items.items():

            raw_value = get_financial_item(df, xbrl_code)
            value = parse_financial_value(raw_value)

            financial_data[name] = value

        print(year, financial_data)

2025 {'CASH': 29086476, 'RECEIVABLES': 38859628, 'INVENTORY': 73660730, 'CURRENT_ASSETS': 174984061, 'TOTAL_ASSETS': 431587329, 'CURRENT_LIABILITIES': 126229330, 'TOTAL_LIABILITIES': 179801035}

In [155]:
print(fin.keys())

dict_keys(['20266Aylık', '20263Aylık', '2025Yıllık', '20259Aylık'])

In [156]:
!pip install kap_sdk

Collecting kap_sdk
  Downloading kap_sdk-0.1.24-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: requests>=2.28.1 in /opt/anaconda3/lib/python3.13/site-packages (from kap_sdk) (2.32.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/lib/python3.13/site-packages (from kap_sdk) (4.13.5)
Collecting pyppeteer>=1.0.2 (from kap_sdk)
  Downloading pyppeteer-2.0.0-py3-none-any.whl.metadata (7.1 kB)
Collecting diskcache>=5.4.0 (from kap_sdk)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: pandas>=1.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from kap_sdk) (2.3.3)
Requirement already satisfied: lxml>=4.9.1 in /opt/anaconda3/lib/python3.13/site-packages (from kap_sdk) (5.3.0)
Requirement already satisfied: tomli>=2.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from kap_sdk) (2.2.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->kap_sdk) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from beautifulsoup4>=4.11.1->kap_sdk) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.5.0->kap_sdk) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.5.0->kap_sdk) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.5.0->kap_sdk) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=1.5.0->kap_sdk) (2025.2)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /opt/anaconda3/lib/python3.13/site-packages (from pyppeteer>=1.0.2->kap_sdk) (1.4.4)
Requirement already satisfied: certifi>=2023 in /opt/anaconda3/lib/python3.13/site-packages (from pyppeteer>=1.0.2->kap_sdk) (2026.1.4)
Requirement already satisfied: importlib-metadata>=1.4 in /opt/anaconda3/lib/python3.13/site-packages (from pyppeteer>=1.0.2->kap_sdk) (8.7.0)
Collecting pyee<12.0.0,>=11.0.0 (from pyppeteer>=1.0.2->kap_sdk)
  Downloading pyee-11.1.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /opt/anaconda3/lib/python3.13/site-packages (from pyppeteer>=1.0.2->kap_sdk) (4.67.1)
Collecting urllib3<2.0.0,>=1.25.8 (from pyppeteer>=1.0.2->kap_sdk)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
Collecting websockets<11.0,>=10.0 (from pyppeteer>=1.0.2->kap_sdk)
  Downloading websockets-10.4.tar.gz (84 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: zipp>=3.20 in /opt/anaconda3/lib/python3.13/site-packages (from importlib-metadata>=1.4->pyppeteer>=1.0.2->kap_sdk) (3.23.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->kap_sdk) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.28.1->kap_sdk) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.28.1->kap_sdk) (3.18)
Downloading kap_sdk-0.1.24-py3-none-any.whl (17 kB)
Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
Downloading pyppeteer-2.0.0-py3-none-any.whl (82 kB)
Downloading pyee-11.1.1-py3-none-any.whl (15 kB)
Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
Building wheels for collected packages: websockets
  Building wheel for websockets (pyproject.toml) ... done
  Created wheel for websockets: filename=websockets-10.4-cp313-cp313-macosx_12_0_arm64.whl size=97802 sha256=d63a2d456c1b21bf2ba78d8172febccb238d647ed2d4e89d1d7f905227bb1ac3
  Stored in directory: /Users/fesavaskurt/Library/Caches/pip/wheels/f5/dd/43/5b7132085406a982d2e0dd808f0ffed137865c8a8c5c7a5e4b
Successfully built websockets
Installing collected packages: websockets, urllib3, pyee, diskcache, pyppeteer, kap_sdk
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [kap_sdk]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.173 requires urllib3>=2.2.2, but you have urllib3 1.26.20 which is incompatible.
Successfully installed diskcache-5.6.3 kap_sdk-0.1.24 pyee-11.1.1 pyppeteer-2.0.0 urllib3-1.26.20 websockets-10.4

In [157]:
import asyncio
from kap_sdk.kap_client import KapClient

async def test():

    client = KapClient()

    company = await client.get_company("ASELS")

    report = await client.get_financial_report(
        company,
        "2022"
    )

    return report

report = await test()

[INFO] Starting Chromium download.
INFO:pyppeteer.chromium_downloader:Starting Chromium download.
100%|██████████| 141M/141M [00:38<00:00, 3.67Mb/s]
[INFO] Beginning extraction
INFO:pyppeteer.chromium_downloader:Beginning extraction
[INFO] Chromium extracted to: /Users/fesavaskurt/Library/Application Support/pyppeteer/local-chromium/1181205
INFO:pyppeteer.chromium_downloader:Chromium extracted to: /Users/fesavaskurt/Library/Application Support/pyppeteer/local-chromium/1181205
ERROR:root:Scraping failed: [Errno 86] Bad CPU type in executable: '/Users/fesavaskurt/Library/Application Support/pyppeteer/local-chromium/1181205/chrome-mac/Chromium.app/Contents/MacOS/Chromium'
WARNING:root:Company with code ASELS not found.

AttributeError: 'NoneType' object has no attribute 'code'

In [159]:
client = KapClient()

company = await client.get_company("ASELS")

print(company)
print(type(company))

ERROR:root:Scraping failed: [Errno 86] Bad CPU type in executable: '/Users/fesavaskurt/Library/Application Support/pyppeteer/local-chromium/1181205/chrome-mac/Chromium.app/Contents/MacOS/Chromium'
WARNING:root:Company with code ASELS not found.

None
<class 'NoneType'>

In [160]:
import inspect
from kap_sdk import _financial_report

print(inspect.getsource(_financial_report))

import requests
from bs4 import BeautifulSoup
from kap_sdk._search_oid import _search_oid
from kap_sdk.models.company import Company
import zipfile
import io
import pandas as pd
from io import StringIO
from typing import List, Dict, Union
import pandas as pd

DOWNLOAD_URL = "https://www.kap.org.tr/tr/api/home-financial/download-file/"


def _download_xls(mkkMemberOid: str, year: str) -> str:
    # Burada dosyayı indiriyor
    data = requests.get(f"{DOWNLOAD_URL}{mkkMemberOid}/{year}/T", stream=False)
    data.raise_for_status()
    return data.content



def _extract_data(path: str, price: float, table_indices: List[int] = [1, 300, 453]) -> List[Dict[str, Union[str, float]]]:
    tables = pd.read_html(path)
    selected_tables = [tables[i].iloc[:, [1, 3]].dropna().reset_index(drop=True) for i in table_indices if i < len(tables)]

    concat_table = pd.concat(selected_tables, ignore_index=True)
    concat_table.columns = ['key', 'value']

    def clean_value(value: str, price: float) -> Union[float, None]:
        try:
            cleaned_value = value.strip().replace(".", "").replace(",", ".")
            return float(cleaned_value) * price
        except ValueError:
            print(f"Could not convert value: {value}")
            return None

    concat_table['value'] = concat_table['value'].apply(lambda x: clean_value(x, price))
    concat_table.dropna(inplace=True)

    extracted_data = []
    for index, row in concat_table.iterrows():
        extracted_data.append({
            "key": row['key'].strip(),
            "value": row['value']
        })

    return extracted_data




def _find_financial_header_title(data: str) -> dict:
    soup = BeautifulSoup(data, 'html.parser')
    header = soup.find('table', {'class': 'financial-header-table'})
    row_title = header.find_all('tr')[1].find_all(
        "td")[1].text.strip().lower().replace(" ", "_")
    row_price = header.find_all('tr')[0].find_all(
        "td")[1].text.strip().replace("TL", "").replace(".", "")

    try:
        price = float(row_price)
    except ValueError:
        price = 1.0

    return {
        "title": row_title,
        "price": price
    }


async def get_financial_report(company: Company, year: str = "2023") -> dict:
    oid = _search_oid(company)
    content = _download_xls(oid, year=year)
    try:
        zip_file = io.BytesIO(content)
        with zipfile.ZipFile(zip_file, 'r') as zip_ref:
            files = zip_ref.namelist()
            if len(files) == 0:
                raise ValueError(
                    f"No found {company.code} financial report for {year}")
            extracted_data = {}
            for file_name in zip_ref.namelist():
                if file_name.endswith('.xls'):
                    with zip_ref.open(file_name) as file:
                        data = file.read()
                    meta = _find_financial_header_title(data)
                    period = f"period_{file_name.split('_')[-1]}_{meta['title']}"
                    period = period.replace('.xls', '')
                    extracted_data[period] = _extract_data(
                        StringIO(data.decode('utf-8')), meta['price'])
    except Exception as e:
        print(f"Error extracting financial report: {e}")
        raise e
    finally:
        pass

    return extracted_data

In [161]:
import inspect
from kap_sdk._search_oid import _search_oid

print(inspect.getsource(_search_oid))

def _search_oid(company: Company) -> dict:
    response = requests.get(f"{URL}{company.code}")
    response.raise_for_status()
    oid = response.json()[0]["mkkMemberOid"]
    if not oid:
        raise Exception(f"Company {company.code} not found.")
    return oid

In [162]:
from kap_sdk import _search_oid

print(_search_oid.URL)

https://www.kap.org.tr/tr/api/member/filter/

In [163]:
import requests

def get_oid(ticker):
    url = f"https://www.kap.org.tr/tr/api/member/filter/{ticker}"

    response = requests.get(url)
    response.raise_for_status()

    data = response.json()

    if not data:
        return None

    return data[0]["mkkMemberOid"]

In [164]:
oid = get_oid("ASELS")
print(oid)

4028e4a1413b7ef401413bc2251e0047

In [165]:
year = 2022

url = (
    f"https://www.kap.org.tr/tr/api/home-financial/"
    f"download-file/{oid}/{year}/T"
)

response = requests.get(url)

print(response.status_code)
print(len(response.content))
print(response.headers.get("Content-Type"))

200
10020716
application/octet-stream

In [166]:
import io
import zipfile

zip_file = io.BytesIO(response.content)

with zipfile.ZipFile(zip_file, "r") as z:
    files = z.namelist()

files

['ASELS_1117839_2022_4.xls',
 'Dönem4Ekler/(0)ASELSAN CMB Report 31.12.2022.pdf',
 'Dönem4Ekler/(1)ASELSAN SPK RAPORU 31.12.2022.pdf',
 'ASELS_1072989_2022_3.xls',
 'Dönem3Ekler/(1)ASELSAN CMB Report 30.09.2022.pdf',
 'Dönem3Ekler/(2)ASELSAN SPK RAPORU 30.09.2022.pdf',
 'ASELS_1054808_2022_2.xls',
 'Dönem2Ekler/(2)ASELSAN CMB Report 30.06.2022.pdf',
 'Dönem2Ekler/(3)ASELSAN SPK RAPORU 30.06.2022.pdf',
 'ASELS_1024084_2022_1.xls',
 'Dönem1Ekler/(3)ASELSAN CMB Report 31.03.2022.pdf',
 'Dönem1Ekler/(4)ASELSAN SPK RAPORU 31.03.2022.pdf']

In [167]:
annual_file = [
    file for file in files
    if file.endswith("_4.xls")
][0]

print(annual_file)

ASELS_1117839_2022_4.xls

In [168]:
with zipfile.ZipFile(zip_file, "r") as z:
    with z.open(annual_file) as file:
        annual_data = file.read()

In [169]:
from io import StringIO

tables = pd.read_html(
    StringIO(annual_data.decode("utf-8"))
)

print(len(tables))

725

In [172]:
for i in range(10):
    print("\nTABLE:", i)
    print("SHAPE:", tables[i].shape)
    display(tables[i].head(10))

TABLE: 0
SHAPE: (2, 2)

                         0          1
0        Sunum Para Birimi   1.000 TL
1  Finansal Tablo Niteliği  Konsolide

TABLE: 1
SHAPE: (595, 5)

,0,1,2,3,4
0,NaN,NaN,NaN,Cari Dönem 31.12.2022,Önceki Dönem 31.12.2021
1,NaN,Finansal Durum Tablosu (Bilanço),NaN,NaN,NaN
2,Finansal Durum Tablosu (Bilanço),NaN,NaN,NaN,NaN
3,NaN,Varlıklar,NaN,NaN,NaN
4,Varlıklar,NaN,NaN,NaN,NaN
5,NaN,DÖNEN VARLIKLAR,NaN,NaN,NaN
6,DÖNEN VARLIKLAR,NaN,NaN,NaN,NaN
7,NaN,Nakit ve Nakit Benzerleri,3.0,5.686.996,2.492.096
8,Nakit ve Nakit Benzerleri,NaN,NaN,NaN,NaN
9,NaN,Gayrimenkul Projeleri Kapsamında Açılan Nakit ...,NaN,NaN,NaN

TABLE: 2
SHAPE: (1, 4)

                                  0   1   2   3
0  Finansal Durum Tablosu (Bilanço) NaN NaN NaN

TABLE: 3
SHAPE: (1, 4)

           0   1   2   3
0  Varlıklar NaN NaN NaN

TABLE: 4
SHAPE: (1, 4)

                 0   1   2   3
0  DÖNEN VARLIKLAR NaN NaN NaN

TABLE: 5
SHAPE: (1, 4)

                           0   1   2   3
0  Nakit ve Nakit Benzerleri NaN NaN NaN

TABLE: 6
SHAPE: (1, 4)

                                                   0   1   2   3
0  Gayrimenkul Projeleri Kapsamında Açılan Nakit ... NaN NaN NaN

TABLE: 7
SHAPE: (1, 4)

                     0   1   2   3
0  Finansal Yatırımlar NaN NaN NaN

TABLE: 8
SHAPE: (1, 4)

                                    0   1   2   3
0  Kullanımı Kısıtlı Banka Bakiyeleri NaN NaN NaN

TABLE: 9
SHAPE: (1, 4)

                   0   1   2   3
0  Vadeli Mevduatlar NaN NaN NaN

In [173]:
df = tables[1]

df.head(20)

,0,1,2,3,4
0,NaN,NaN,NaN,Cari Dönem 31.12.2022,Önceki Dönem 31.12.2021
1,NaN,Finansal Durum Tablosu (Bilanço),NaN,NaN,NaN
2,Finansal Durum Tablosu (Bilanço),NaN,NaN,NaN,NaN
3,NaN,Varlıklar,NaN,NaN,NaN
4,Varlıklar,NaN,NaN,NaN,NaN
5,NaN,DÖNEN VARLIKLAR,NaN,NaN,NaN
6,DÖNEN VARLIKLAR,NaN,NaN,NaN,NaN
7,NaN,Nakit ve Nakit Benzerleri,3.0,5.686.996,2.492.096
8,Nakit ve Nakit Benzerleri,NaN,NaN,NaN,NaN
9,NaN,Gayrimenkul Projeleri Kapsamında Açılan Nakit ...,NaN,NaN,NaN
10,Gayrimenkul Projeleri Kapsamında Açılan Nakit ...,NaN,NaN,NaN,NaN
11,NaN,Finansal Yatırımlar,NaN,0,0
12,Finansal Yatırımlar,NaN,NaN,NaN,NaN
13,NaN,Kullanımı Kısıtlı Banka Bakiyeleri,NaN,NaN,NaN
14,Kullanımı Kısıtlı Banka Bakiyeleri,NaN,NaN,NaN,NaN
15,NaN,Vadeli Mevduatlar,NaN,NaN,NaN
16,Vadeli Mevduatlar,NaN,NaN,NaN,NaN
17,NaN,Satılmaya Hazır Finansal Varlıklar,NaN,NaN,NaN
18,Satılmaya Hazır Finansal Varlıklar,NaN,NaN,NaN,NaN
19,NaN,Vadeye Kadar Elde Tutulacak Finansal Yatırımlar,NaN,NaN,NaN

In [174]:
df[
    df[1].astype(str).str.strip() == "Nakit ve Nakit Benzerleri"
]

     0                          1    2          3          4
7  NaN  Nakit ve Nakit Benzerleri  3.0  5.686.996  2.492.096

In [175]:
def get_financial_item(df, item_name):

    mask = (
        df[1]
        .astype(str)
        .str.strip()
        .eq(item_name)
    )

    selected_row = df[mask]

    if selected_row.empty:
        return np.nan

    return selected_row[3].iloc[0]

In [176]:
get_financial_item(
    df,
    "Nakit ve Nakit Benzerleri"
)

'5.686.996'

In [177]:
raw_value = get_financial_item(
    df,
    "Nakit ve Nakit Benzerleri"
)

value = parse_financial_value(raw_value)

print(value)

5686996

In [179]:
items = (
    df[1]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
)

for item in items:
    print(item)

Finansal Durum Tablosu (Bilanço)
Varlıklar
DÖNEN VARLIKLAR
Nakit ve Nakit Benzerleri
Gayrimenkul Projeleri Kapsamında Açılan Nakit Hesapları
Finansal Yatırımlar
Kullanımı Kısıtlı Banka Bakiyeleri
Vadeli Mevduatlar
Satılmaya Hazır Finansal Varlıklar
Vadeye Kadar Elde Tutulacak Finansal Yatırımlar
Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtılan Finansal Varlıklar
Alım Satım Amaçlı Elde Tutulan Finansal Varlıklar
Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtılarak Ölçülen Diğer Finansal Varlıklar
Gerçeğe Uygun Değer Farkı Kar/Zarara Yansıtılan Olarak Sınıflandırılan Finansal Varlıklar
Yatırım Riski Hayat Poliçesi Sahiplerine Ait Finansal Yatırımlar
Gerçeğe Uygun Değer Farkı Diğer Kapsamlı Gelire Yansıtılan Finansal Varlıklar
Gerçeğe Uygun Değer Farkı Diğer Kapsamlı Gelire Yansıtılarak Ölçülen Finansal Varlıklar
Özkaynağa Dayalı Finansal Araçlara Yapılan Yatırımlar
İtfa Edilmiş Maliyetiyle Ölçülen Finansal Varlıklar
Diğer Finansal Yatırımlar
Teminata Verilen Finansal Varlıklar
Ticari Alacaklar
İlişkili Taraflardan Ticari Alacaklar
İlişkili Olmayan Taraflardan Ticari Alacaklar
Finans Sektörü Faaliyetlerinden Alacaklar
Finans Sektörü Faaliyetlerinden İlişkili Taraflardan Alacaklar
Finans Sektörü Faaliyetlerinden İlişkili Olmayan Taraflardan Alacaklar
Türkiye Cumhuriyet Merkez Bankası Hesabı
Diğer Alacaklar
İlişkili Taraflardan Diğer Alacaklar
İlişkili Olmayan Taraflardan Diğer Alacaklar
Müşteri Sözleşmelerinden Doğan Varlıklar
Devam Eden İnşaat ve Taahhüt İşlerinden Doğan Sözleşme Varlıkları
Mal ve Hizmet Satışlarından Doğan Sözleşme Varlıkları
Diğer Sözleşme Varlıkları
İmtiyaz Sözleşmelerine İlişkin Finansal Varlıklar
Türev Araçlar
Alım Satım Amaçlı Türev Araçlar
Riskten Korunma Amaçlı Türev Araçlar
Stoklar
Proje Halindeki Stoklar
Canlı Varlıklar
Peşin Ödenmiş Giderler
İlişkili Taraflara Peşin Ödenmiş Giderler
İlişkili Olmayan Taraflara Peşin Ödenmiş Giderler
Ertelenmiş Sigortacılık Üretim Giderleri
Cari Dönem Vergisiyle İlgili Varlıklar
Nakit Dışı Serbest Kullanılabilir Teminatlar
Diğer Dönen Varlıklar
İlişkili Taraflardan Diğer Dönen Varlıklar
İlişkili Olmayan Taraflardan Diğer Dönen Varlıklar
ARA TOPLAM
Satış Amaçlı Sınıflandırılan Duran Varlıklar
Ortaklara Dağıtılmak Üzere Elde Tutulan Duran Varlıklar
TOPLAM DÖNEN VARLIKLAR
DURAN VARLIKLAR
Satılmaya Hazır Finansal Yatırımlar
İştirakler, İş Ortaklıkları ve Bağlı Ortaklıklardaki Yatırımlar
Özkaynak Yöntemiyle Değerlenen Yatırımlar
Yatırım Amaçlı Gayrimenkuller
Proje Halindeki Yatırım Amaçlı Gayrimenkuller
Maddi Duran Varlıklar
Arazi ve Arsalar
Yeraltı ve Yerüstü Düzenlemeleri
Binalar
Tesis, Makine ve Cihazlar
Taşıtlar
Mobilya ve Demirbaşlar
Özel Maliyetler
Taşıyıcı Bitkiler
Özel Tükenmeye Tabi Varlıklar
Yapılmakta Olan Yatırımlar
Faaliyet Kiralamasına Konu Varlıklar
Diğer Maddi Duran Varlıklar
Kullanım Hakkı Varlıkları
Maddi Olmayan Duran Varlıklar
Şerefiye
İmtiyaz Sözleşmelerinden Doğan Haklar
Diğer Haklar
Patentler
Markalar
Lisanslar
Bilgisayar Yazılımları
Aktifleştirilen Geliştirme Maliyetleri
Diğer Maddi Olmayan Duran Varlıklar
Ertelenmiş Vergi Varlığı
Cari Dönem Vergisiyle İlgili Duran Varlıklar
Diğer Duran Varlıklar
İlişkili Taraflara İlişkin Diğer Duran Varlıklar
İlişkili Olmayan Taraflara İlişkin Diğer Duran Varlıklar
TOPLAM DURAN VARLIKLAR
TOPLAM VARLIKLAR
KAYNAKLAR
KISA VADELİ YÜKÜMLÜLÜKLER
Kısa Vadeli Borçlanmalar
İlişkili Taraflardan Kısa Vadeli Borçlanmalar
Banka Kredileri
Kiralama İşlemlerinden Borçlar
İhraç Edilmiş Borçlanma Araçları
Diğer Kısa Vadeli Borçlanmalar
İlişkili Olmayan Taraflardan Kısa Vadeli Borçlanmalar
Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
İlişkili Taraflardan Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
Diğer Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
İlişkili Olmayan Taraflardan Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
Diğer Finansal Yükümlülükler
Kontrol Gücü Olmayan Paylara İlişkin Satış Opsiyon Yükümlülükleri
Finansal Teminat Sözleşmeleri
Diğer Muhtelif Finansal Yükümlülükler
Ticari Borçlar
İlişkili Taraflara Ticari Borçlar
İlişkili Olmayan Taraflara Ticari Borçlar
Finans Sektörü Faaliyetlerinden Borçlar
Finans Sektörü Faaliyetlerinden İlişkili Taraflara Borçlar
Finans Sektörü Faaliyetlerinden İlişkili Olmayan Taraflara Borçlar
Çalışanlara Sağlanan Faydalar Kapsamında Borçlar
Diğer Borçlar
İlişkili Taraflara Diğer Borçlar
İlişkili Olmayan Taraflara Diğer Borçlar
Müşteri Sözleşmelerinden Doğan Yükümlülükler
Devam Eden İnşaat ve Taahhüt İşlerinden Doğan Sözleşme Yükümlülükleri
Mal ve Hizmet Satışlarından Doğan Sözleşme Yükümlülükleri
Diğer Sözleşme Yükümlülükleri
Özkaynak Yöntemiyle Değerlenen Yatırımlardan Yükümlülükler
Devlet Teşvik ve Yardımları
Ertelenmiş Gelirler (Müşteri Sözleşmelerinden Doğan Yükümlülüklerin Dışında Kalanlar)
İlişkili Taraflardan Ertelenmiş Gelirler (Müşteri Sözleşmelerinden Doğan Yükümlülüklerin Dışında Kalanlar)
İlişkili Olmayan Taraflardan Ertelenmiş Gelirler (Müşteri Sözleşmelerinden Doğan Yükümlülüklerin Dışında Kalanlar)
Dönem Karı Vergi Yükümlülüğü
Kısa Vadeli Karşılıklar
Çalışanlara Sağlanan Faydalara İlişkin Kısa Vadeli Karşılıklar
Sigortacılık Teknik Karşılıkları
Diğer Kısa Vadeli Karşılıklar
Diğer Kısa Vadeli Yükümlülükler
İlişkili Taraflara Diğer Kısa Vadeli Yükümlülükler
İlişkili Olmayan Taraflara Diğer Kısa Vadeli Yükümlülükler
Satış Amaçlı Sınıflandırılan Varlık Gruplarına İlişkin Yükümlülükler
Ortaklara Dağıtılmak Üzere Elde Tutulan Varlık Gruplarına İlişkin Yükümlülükler
TOPLAM KISA VADELİ YÜKÜMLÜLÜKLER
UZUN VADELİ YÜKÜMLÜLÜKLER
Uzun Vadeli Borçlanmalar
İlişkili Taraflardan Uzun Vadeli Borçlanmalar
Diğer Uzun Vadeli Borçlanmalar
İlişkili Olmayan Taraflardan Uzun Vadeli Borçlanmalar
Uzun Vadeli Karşılıklar
Çalışanlara Sağlanan Faydalara İlişkin Uzun Vadeli Karşılıklar
Genel Karşılıklar
Muhtemel Riskler İçin Ayrılan Serbest Karşılıklar
Diğer Uzun Vadeli Karşılıklar
Cari Dönem Vergisiyle İlgili Borçlar
Ertelenmiş Vergi Yükümlülüğü
Diğer Uzun Vadeli Yükümlülükler
İlişkili Taraflara Diğer Uzun Vadeli Yükümlülükler
İlişkili Olmayan Taraflara Diğer Uzun Vadeli Yükümlülükler
TOPLAM UZUN VADELİ YÜKÜMLÜLÜKLER
TOPLAM YÜKÜMLÜLÜKLER
ÖZKAYNAKLAR
Ana Ortaklığa Ait Özkaynaklar
Ödenmiş Sermaye
Sermaye Düzeltme Farkları
Birleşme Denkleştirme Hesabı
Pay Sahiplerinin İlave Sermaye Katkıları
Sermaye Avansı
Geri Alınmış Paylar (-)
Karşılıklı İştirak Sermaye Düzeltmesi (-)
Paylara İlişkin Primler (İskontolar)
Ortak Kontrole Tabi Teşebbüs veya İşletmeleri İçeren Birleşmelerin Etkisi
Kontrol Gücü Olmayan Paylara İlişkin Satış Opsiyon Değerleme Fonu
Pay Bazlı Ödemeler (-)
Kar veya Zararda Yeniden Sınıflandırılmayacak Birikmiş Diğer Kapsamlı Gelirler (Giderler)
Özkaynağa Dayalı Finansal Araçlara Yatırımlardan Kaynaklanan Kazançlar (Kayıplar)
Yeniden Değerleme ve Ölçüm Kazançları (Kayıpları)
Maddi Duran Varlık Yeniden Değerleme Artışları (Azalışları)
Maddi Olmayan Duran Varlık Yeniden Değerleme Artışları (Azalışları)
Kullanım Hakkı Varlıkları Yeniden Değerleme Artışları (Azalışları)
Tanımlanmış Fayda Planları Yeniden Ölçüm Kazançları (Kayıpları)
Diğer Yeniden Değerleme ve Ölçüm Kazançları (Kayıpları)
Kredi Riskindeki Değişikliğe Bağlı Olarak Finansal Yükümlülüğün Gerçeğe Uygun Değerindeki Değişikliklerden Kaynaklanan Kazançlar (Kayıplar)
Özkaynağa Dayalı Finansal Araçlara Yapılan Yatırımlara İlişkin Finansal Riskten Korunma Kazançları (Kayıpları)
Özkaynak Yöntemi ile Değerlenen Yatırımların Diğer Kapsamlı Gelirinden Kar veya Zararda Sınıflandırılmayacak Paylar
Yabancı Para Çevrim Farkları
Diğer Kazançlar (Kayıplar)
Kar veya Zararda Yeniden Sınıflandırılacak Birikmiş Diğer Kapsamlı Gelirler (Giderler)
Riskten Korunma Kazançları (Kayıpları)
Nakit Akış Riskinden Korunma Kazançları (Kayıpları)
Yurtdışındaki İşletmeye İlişkin Yatırım Riskinden Korunma Kazançları (Kayıpları)
Diğer Riskten Korunma Kazançları (Kayıpları)
Yeniden Değerleme ve Sınıflandırma Kazançları (Kayıpları)
Satılmaya Hazır Finansal Varlıkların Yeniden Değerleme ve/veya Sınıflandırma Kazançları (Kayıpları)
Gerçeğe Uygun Değer Farkı Diğer Kapsamlı Gelire Yansıtılan Finansal Varlıklardan Kazançlar (Kayıplar)
Diğer Yeniden Değerleme ve Sınıflandırma Kazançları (Kayıpları)
Opsiyonların Zaman Değerindeki Değişiklikler
Forward Sözleşmesinin Forward Bileşeninin Değerindeki Değişiklikler
Yabancı Para Alım Satım Marjlarındaki Değişiklikler
Özkaynak Yöntemi ile Değerlenen Yatırımların Diğer Kapsamlı Gelirinden Kar/Zararda Sınıflandırılacak Paylar
Kardan Ayrılan Kısıtlanmış Yedekler
Sermayeye Eklenecek Gayrimenkul veya İştirak Satış Kazancı
Yasal Yedekler
Geri Alınan Paylara İlişkin Yedekler
Girişim Sermayesi Fonu
Diğer Kısıtlanmış Yedekler
Diğer Özkaynak Payları
Diğer Yedekler
Ödenen Kar Payı Avansları (Net) (-)
Geçmiş Yıllar Karları veya Zararları
Net Dönem Karı veya Zararı
Kontrol Gücü Olmayan Paylar
TOPLAM ÖZKAYNAKLAR
TOPLAM KAYNAKLAR

In [180]:
keywords = [
    "Nakit",
    "Ticari Alacak",
    "Stok",
    "Dönen Varlık",
    "Toplam Varlık",
    "Kısa Vadeli",
    "Toplam Yükümlülük",
    "Özkaynak",
    "Hasılat",
    "Brüt",
    "Esas Faaliyet",
    "Net Dönem",
    "Nakit Akış"
]

for item in items:
    if any(keyword.lower() in item.lower() for keyword in keywords):
        print(item)

Nakit ve Nakit Benzerleri
Gayrimenkul Projeleri Kapsamında Açılan Nakit Hesapları
Ticari Alacaklar
İlişkili Taraflardan Ticari Alacaklar
İlişkili Olmayan Taraflardan Ticari Alacaklar
Stoklar
Proje Halindeki Stoklar
Nakit Dışı Serbest Kullanılabilir Teminatlar
Diğer Dönen Varlıklar
İlişkili Taraflardan Diğer Dönen Varlıklar
İlişkili Olmayan Taraflardan Diğer Dönen Varlıklar
Özkaynak Yöntemiyle Değerlenen Yatırımlar
Kısa Vadeli Borçlanmalar
İlişkili Taraflardan Kısa Vadeli Borçlanmalar
Diğer Kısa Vadeli Borçlanmalar
İlişkili Olmayan Taraflardan Kısa Vadeli Borçlanmalar
Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
İlişkili Taraflardan Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
Diğer Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
İlişkili Olmayan Taraflardan Uzun Vadeli Borçlanmaların Kısa Vadeli Kısımları
Özkaynak Yöntemiyle Değerlenen Yatırımlardan Yükümlülükler
Kısa Vadeli Karşılıklar
Çalışanlara Sağlanan Faydalara İlişkin Kısa Vadeli Karşılıklar
Diğer Kısa Vadeli Karşılıklar
Diğer Kısa Vadeli Yükümlülükler
İlişkili Taraflara Diğer Kısa Vadeli Yükümlülükler
İlişkili Olmayan Taraflara Diğer Kısa Vadeli Yükümlülükler
TOPLAM YÜKÜMLÜLÜKLER
ÖZKAYNAKLAR
Ana Ortaklığa Ait Özkaynaklar
Özkaynak Yöntemi ile Değerlenen Yatırımların Diğer Kapsamlı Gelirinden Kar veya Zararda Sınıflandırılmayacak Paylar
Nakit Akış Riskinden Korunma Kazançları (Kayıpları)
Özkaynak Yöntemi ile Değerlenen Yatırımların Diğer Kapsamlı Gelirinden Kar/Zararda Sınıflandırılacak Paylar
Diğer Özkaynak Payları
Net Dönem Karı veya Zararı
TOPLAM ÖZKAYNAKLAR

In [181]:
search_words = [
    "VARLIKLAR",
    "YÜKÜMLÜLÜKLER",
    "ÖZKAYNAKLAR"
]

for item in items:
    if any(word.lower() in item.lower() for word in search_words):
        print(item)

DÖNEN VARLIKLAR
TOPLAM DÖNEN VARLIKLAR
DURAN VARLIKLAR
TOPLAM DURAN VARLIKLAR
TOPLAM VARLIKLAR
KISA VADELİ YÜKÜMLÜLÜKLER
Diğer Finansal Yükümlülükler
Kontrol Gücü Olmayan Paylara İlişkin Satış Opsiyon Yükümlülükleri
Diğer Muhtelif Finansal Yükümlülükler
Müşteri Sözleşmelerinden Doğan Yükümlülükler
Devam Eden İnşaat ve Taahhüt İşlerinden Doğan Sözleşme Yükümlülükleri
Mal ve Hizmet Satışlarından Doğan Sözleşme Yükümlülükleri
Diğer Sözleşme Yükümlülükleri
Özkaynak Yöntemiyle Değerlenen Yatırımlardan Yükümlülükler
Ertelenmiş Gelirler (Müşteri Sözleşmelerinden Doğan Yükümlülüklerin Dışında Kalanlar)
İlişkili Taraflardan Ertelenmiş Gelirler (Müşteri Sözleşmelerinden Doğan Yükümlülüklerin Dışında Kalanlar)
İlişkili Olmayan Taraflardan Ertelenmiş Gelirler (Müşteri Sözleşmelerinden Doğan Yükümlülüklerin Dışında Kalanlar)
Diğer Kısa Vadeli Yükümlülükler
İlişkili Taraflara Diğer Kısa Vadeli Yükümlülükler
İlişkili Olmayan Taraflara Diğer Kısa Vadeli Yükümlülükler
Satış Amaçlı Sınıflandırılan Varlık Gruplarına İlişkin Yükümlülükler
Ortaklara Dağıtılmak Üzere Elde Tutulan Varlık Gruplarına İlişkin Yükümlülükler
TOPLAM KISA VADELİ YÜKÜMLÜLÜKLER
UZUN VADELİ YÜKÜMLÜLÜKLER
Diğer Uzun Vadeli Yükümlülükler
İlişkili Taraflara Diğer Uzun Vadeli Yükümlülükler
İlişkili Olmayan Taraflara Diğer Uzun Vadeli Yükümlülükler
TOPLAM UZUN VADELİ YÜKÜMLÜLÜKLER
TOPLAM YÜKÜMLÜLÜKLER
ÖZKAYNAKLAR
Ana Ortaklığa Ait Özkaynaklar
TOPLAM ÖZKAYNAKLAR

In [182]:
financial_items = {
    "CASH": "Nakit ve Nakit Benzerleri",
    "RECEIVABLES": "Ticari Alacaklar",
    "INVENTORY": "Stoklar",
    "CURRENT_ASSETS": "TOPLAM DÖNEN VARLIKLAR",
    "TOTAL_ASSETS": "TOPLAM VARLIKLAR",
    "CURRENT_LIABILITIES": "TOPLAM KISA VADELİ YÜKÜMLÜLÜKLER",
    "NONCURRENT_LIABILITIES": "TOPLAM UZUN VADELİ YÜKÜMLÜLÜKLER",
    "TOTAL_LIABILITIES": "TOPLAM YÜKÜMLÜLÜKLER",
    "EQUITY": "TOPLAM ÖZKAYNAKLAR"
}

In [183]:
financial_data = {}

for name, item_name in financial_items.items():

    raw_value = get_financial_item(
        df,
        item_name
    )

    value = parse_financial_value(raw_value)

    financial_data[name] = value

financial_data

{'CASH': 5686996,
 'RECEIVABLES': 14888340,
 'INVENTORY': 12592653,
 'CURRENT_ASSETS': 38299445,
 'TOTAL_ASSETS': 76043841,
 'CURRENT_LIABILITIES': 29651397,
 'NONCURRENT_LIABILITIES': 6531475,
 'TOTAL_LIABILITIES': 36182872,
 'EQUITY': 39860969}

In [185]:
net_income_rows = df[
    df[1].astype(str).str.strip() == "Net Dönem Karı veya Zararı"
]

net_income_rows

       0                           1   2           3          4
587  NaN  Net Dönem Karı veya Zararı NaN  11.915.661  7.130.563

In [186]:
idx = net_income_rows.index[0]

display(
    df.loc[idx-30:idx+10, [1, 3, 4]]
)

                                                     1           3           4
557       Opsiyonların Zaman Değerindeki Değişiklikler         NaN         NaN
558                                                NaN         NaN         NaN
559  Forward Sözleşmesinin Forward Bileşeninin Değe...         NaN         NaN
560                                                NaN         NaN         NaN
561  Yabancı Para Alım Satım Marjlarındaki Değişikl...         NaN         NaN
562                                                NaN         NaN         NaN
563  Özkaynak Yöntemi ile Değerlenen Yatırımların D...         NaN         NaN
564                                                NaN         NaN         NaN
565                         Diğer Kazançlar (Kayıplar)         NaN         NaN
566                                                NaN         NaN         NaN
567                Kardan Ayrılan Kısıtlanmış Yedekler     612.077     542.341
568                                                NaN         NaN         NaN
569  Sermayeye Eklenecek Gayrimenkul veya İştirak S...         NaN         NaN
570                                                NaN         NaN         NaN
571                                     Yasal Yedekler         NaN         NaN
572                                                NaN         NaN         NaN
573               Geri Alınan Paylara İlişkin Yedekler         NaN         NaN
574                                                NaN         NaN         NaN
575                             Girişim Sermayesi Fonu         NaN         NaN
576                                                NaN         NaN         NaN
577                         Diğer Kısıtlanmış Yedekler         NaN         NaN
578                                                NaN         NaN         NaN
579                             Diğer Özkaynak Payları         NaN         NaN
580                                                NaN         NaN         NaN
581                                     Diğer Yedekler         NaN         NaN
582                                                NaN         NaN         NaN
583                Ödenen Kar Payı Avansları (Net) (-)         NaN         NaN
584                                                NaN         NaN         NaN
585               Geçmiş Yıllar Karları veya Zararları  16.951.819  10.350.992
586                                                NaN         NaN         NaN
587                         Net Dönem Karı veya Zararı  11.915.661   7.130.563
588                                                NaN         NaN         NaN
589                        Kontrol Gücü Olmayan Paylar     223.987     271.768
590                                                NaN         NaN         NaN
591                                 TOPLAM ÖZKAYNAKLAR  39.860.969  25.835.210
592                                                NaN         NaN         NaN
593                                   TOPLAM KAYNAKLAR  76.043.841  46.413.298
594                                                NaN         NaN         NaN

In [187]:
display(tables[300].head(30))

,0,1,2,3,4
0,NaN,NaN,NaN,Cari Dönem 01.01.2022 - 31.12.2022,Önceki Dönem 01.01.2021 - 31.12.2021
1,NaN,Kar veya Zarar ve Diğer Kapsamlı Gelir Tablosu,NaN,NaN,NaN
2,Kar veya Zarar ve Diğer Kapsamlı Gelir Tablosu,NaN,NaN,NaN,NaN
3,NaN,KAR VEYA ZARAR KISMI,NaN,NaN,NaN
4,KAR VEYA ZARAR KISMI,NaN,NaN,NaN,NaN
5,NaN,Hasılat,20,35.281.677,20.138.953
6,Hasılat,NaN,NaN,NaN,NaN
7,NaN,Satışların Maliyeti,20,-23.498.222,-13.490.042
8,Satışların Maliyeti,NaN,NaN,NaN,NaN
9,NaN,TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR),NaN,11.783.455,6.648.911
10,TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR),NaN,NaN,NaN,NaN
11,NaN,Finans Sektörü Faaliyetleri Hasılatı,NaN,NaN,NaN
12,Finans Sektörü Faaliyetleri Hasılatı,NaN,NaN,NaN,NaN
13,NaN,"Ücret, Prim, Komisyon ve Diğer Hizmet Gelirleri",NaN,NaN,NaN
14,"Ücret, Prim, Komisyon ve Diğer Hizmet Gelirleri",NaN,NaN,NaN,NaN
15,NaN,Kambiyo Gelirleri,NaN,NaN,NaN
16,Kambiyo Gelirleri,NaN,NaN,NaN,NaN
17,NaN,Faiz Gelirleri,NaN,NaN,NaN
18,Faiz Gelirleri,NaN,NaN,NaN,NaN
19,NaN,Kar Payı Gelirleri,NaN,NaN,NaN
20,Kar Payı Gelirleri,NaN,NaN,NaN,NaN
21,NaN,Türev Finansal İşlemlerden Kazanç,NaN,NaN,NaN
22,Türev Finansal İşlemlerden Kazanç,NaN,NaN,NaN,NaN
23,NaN,Portföy İşletmeciliği Faaliyetinden Elde Edile...,NaN,NaN,NaN
24,Portföy İşletmeciliği Faaliyetinden Elde Edile...,NaN,NaN,NaN,NaN
25,NaN,Sigortacılık Hizmetlerinden Elde Edilen Gelir,NaN,NaN,NaN
26,Sigortacılık Hizmetlerinden Elde Edilen Gelir,NaN,NaN,NaN,NaN
27,NaN,Emeklilik Hizmetlerinden Elde Edilen Gelir,NaN,NaN,NaN
28,Emeklilik Hizmetlerinden Elde Edilen Gelir,NaN,NaN,NaN,NaN
29,NaN,Finansal Varlık ve Yükümlülüklere İlişkin Gerç...,NaN,NaN,NaN

In [191]:
income_df = tables[300]

In [192]:
keywords = [
    "ESAS FAALİYET",
    "FAALİYET KARI",
    "DÖNEM KARI",
    "DÖNEM ZARARI"
]

income_items = (
    income_df[1]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
)

for item in income_items:
    if any(keyword.lower() in item.lower() for keyword in keywords):
        print(item)

ESAS FAALİYET KARI (ZARARI)
FİNANSMAN GELİRİ (GİDERİ) ÖNCESİ FAALİYET KARI (ZARARI)
SÜRDÜRÜLEN FAALİYETLER DÖNEM KARI (ZARARI)
DURDURULAN FAALİYETLER DÖNEM KARI (ZARARI)
DÖNEM KARI (ZARARI)

In [193]:
income_items = {
    "REVENUE": "Hasılat",
    "GROSS_PROFIT": "TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR)",
    "OPERATING_PROFIT": "ESAS FAALİYET KARI (ZARARI)",
    "NET_INCOME": "DÖNEM KARI (ZARARI)"
}

In [194]:
for name, item_name in income_items.items():

    raw_value = get_financial_item(
        income_df,
        item_name
    )

    value = parse_financial_value(raw_value)

    financial_data[name] = value

financial_data

{'CASH': 5686996,
 'RECEIVABLES': 14888340,
 'INVENTORY': 12592653,
 'CURRENT_ASSETS': 38299445,
 'TOTAL_ASSETS': 76043841,
 'CURRENT_LIABILITIES': 29651397,
 'NONCURRENT_LIABILITIES': 6531475,
 'TOTAL_LIABILITIES': 36182872,
 'EQUITY': 39860969,
 'REVENUE': 35281677,
 'GROSS_PROFIT': 11783455,
 'OPERATING_PROFIT': 12089992,
 'NET_INCOME': 11868109}

In [195]:
cash_flow_df = tables[453]

display(cash_flow_df.head(20))
print(cash_flow_df.shape)

,0,1,2,3,4
0,NaN,NaN,NaN,Cari Dönem 01.01.2022 - 31.12.2022,Önceki Dönem 01.01.2021 - 31.12.2021
1,NaN,Nakit Akış Tablosu (Dolaylı Yöntem),NaN,NaN,NaN
2,Nakit Akış Tablosu (Dolaylı Yöntem),NaN,NaN,NaN,NaN
3,NaN,İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI,NaN,5.761.731,2.432.551
4,İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI,NaN,NaN,NaN,NaN
5,NaN,Dönem Karı (Zararı),NaN,11.868.109,7.127.341
6,Dönem Karı (Zararı),NaN,NaN,NaN,NaN
7,NaN,Sürdürülen Faaliyetlerden Dönem Karı (Zararı),NaN,NaN,NaN
8,Sürdürülen Faaliyetlerden Dönem Karı (Zararı),NaN,NaN,NaN,NaN
9,NaN,Durdurulan Faaliyetlerden Dönem Karı (Zararı),NaN,NaN,NaN
10,Durdurulan Faaliyetlerden Dönem Karı (Zararı),NaN,NaN,NaN,NaN
11,NaN,Dönem Net Karı (Zararı) Mutabakatı İle İlgili ...,NaN,6.784.134,6.098.771
12,Dönem Net Karı (Zararı) Mutabakatı İle İlgili ...,NaN,NaN,NaN,NaN
13,NaN,Amortisman ve İtfa Gideri İle İlgili Düzeltmeler,11-12,588.934,432.191
14,Amortisman ve İtfa Gideri İle İlgili Düzeltmeler,NaN,NaN,NaN,NaN
15,NaN,Değer Düşüklüğü (İptali) İle İlgili Düzeltmeler,NaN,204,41.086
16,Değer Düşüklüğü (İptali) İle İlgili Düzeltmeler,NaN,NaN,NaN,NaN
17,NaN,Alacaklarda Değer Düşüklüğü (İptali) ile İlgil...,6,148,7.730
18,Alacaklarda Değer Düşüklüğü (İptali) ile İlgil...,NaN,NaN,NaN,NaN
19,NaN,Diğer Finansal Varlıklar veya Yatırımlar Değer...,NaN,NaN,NaN

(407, 5)

In [196]:
cash_flow_items = (
    cash_flow_df[1]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
)

keywords = [
    "FAALİYETLERDEN",
    "İŞLETME FAALİYET",
    "NAKİT AKIŞ"
]

for item in cash_flow_items:
    if any(keyword.lower() in item.lower() for keyword in keywords):
        print(item)

İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI
YATIRIM FAALİYETLERİNDEN KAYNAKLANAN NAKİT AKIŞLARI
FİNANSMAN FAALİYETLERİNDEN NAKİT AKIŞLARI

In [197]:
cash_flow_items = {
    "OPERATING_CASH_FLOW": "İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI"
}

for name, item_name in cash_flow_items.items():

    raw_value = get_financial_item(
        cash_flow_df,
        item_name
    )

    value = parse_financial_value(raw_value)

    financial_data[name] = value

financial_data

{'CASH': 5686996,
 'RECEIVABLES': 14888340,
 'INVENTORY': 12592653,
 'CURRENT_ASSETS': 38299445,
 'TOTAL_ASSETS': 76043841,
 'CURRENT_LIABILITIES': 29651397,
 'NONCURRENT_LIABILITIES': 6531475,
 'TOTAL_LIABILITIES': 36182872,
 'EQUITY': 39860969,
 'REVENUE': 35281677,
 'GROSS_PROFIT': 11783455,
 'OPERATING_PROFIT': 12089992,
 'NET_INCOME': 11868109,
 'OPERATING_CASH_FLOW': 5761731}

In [247]:
def get_company_financials(ticker, year):

    # =====================================================
    # 1. RAPORU AL
    # =====================================================

    tables, annual_file = get_annual_report_tables(
        ticker=ticker,
        year=year
    )


    # =====================================================
    # 2. FİNANSAL TABLOLARI BUL
    # =====================================================

    # Bilanço
    balance_sheet = find_main_table(
        tables,
        [
            "TOPLAM VARLIKLAR",
            "TOPLAM ÖZKAYNAKLAR"
        ]
    )

    # Gelir tablosu
    income_statement = find_main_table(
        tables,
        [
            "Hasılat",
            "DÖNEM KARI (ZARARI)"
        ]
    )

    # Nakit akış tablosu
    cash_flow_statement = find_main_table(
        tables,
        [
            "İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI"
        ]
    )


    # =====================================================
    # 3. BİLANÇO KALEMLERİ
    # =====================================================

    balance_items = {

        "CASH":
            "Nakit ve Nakit Benzerleri",

        "RECEIVABLES":
            "Ticari Alacaklar",

        "INVENTORY":
            "Stoklar",

        "CURRENT_ASSETS":
            "TOPLAM DÖNEN VARLIKLAR",

        "TOTAL_ASSETS":
            "TOPLAM VARLIKLAR",

        "CURRENT_LIABILITIES":
            "TOPLAM KISA VADELİ YÜKÜMLÜLÜKLER",

        "NONCURRENT_LIABILITIES":
            "TOPLAM UZUN VADELİ YÜKÜMLÜLÜKLER",

        "TOTAL_LIABILITIES":
            "TOPLAM YÜKÜMLÜLÜKLER",

        "EQUITY":
            "TOPLAM ÖZKAYNAKLAR"
    }


    # =====================================================
    # 4. GELİR TABLOSU KALEMLERİ
    # =====================================================

    income_items = {

        "REVENUE":
            "Hasılat",

        "GROSS_PROFIT":
            "TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR)",

        "OPERATING_PROFIT":
            "ESAS FAALİYET KARI (ZARARI)",

        "NET_INCOME":
            "DÖNEM KARI (ZARARI)"
    }


    # =====================================================
    # 5. NAKİT AKIŞ KALEMLERİ
    # =====================================================

    cash_flow_items = {

        "OPERATING_CASH_FLOW":
            "İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI"
    }


    # =====================================================
    # 6. SONUÇ DICTIONARY
    # =====================================================

    financial_data = {

        "TICKER": ticker,
        "YEAR": year,
        "KAP_FILE": annual_file
    }


    # =====================================================
    # 7. BİLANÇO
    # =====================================================

    for name, item_name in balance_items.items():

        raw_value = get_financial_item(
            balance_sheet,
            item_name
        )

        financial_data[name] = parse_financial_value(
            raw_value
        )


    # =====================================================
    # 8. GELİR TABLOSU
    # =====================================================

    for name, item_name in income_items.items():

        raw_value = get_financial_item(
            income_statement,
            item_name
        )

        financial_data[name] = parse_financial_value(
            raw_value
        )


    # =====================================================
    # 9. NAKİT AKIŞ TABLOSU
    # =====================================================

    for name, item_name in cash_flow_items.items():

        raw_value = get_financial_item(
            cash_flow_statement,
            item_name
        )

        financial_data[name] = parse_financial_value(
            raw_value
        )


    return financial_data

In [200]:
asels_2022 = get_company_financials(
    ticker="ASELS",
    year=2022
)

asels_2022

{'TICKER': 'ASELS',
 'YEAR': 2022,
 'CASH': 5686996,
 'RECEIVABLES': 14888340,
 'INVENTORY': 12592653,
 'CURRENT_ASSETS': 38299445,
 'TOTAL_ASSETS': 76043841,
 'CURRENT_LIABILITIES': 29651397,
 'NONCURRENT_LIABILITIES': 6531475,
 'TOTAL_LIABILITIES': 36182872,
 'EQUITY': 39860969,
 'REVENUE': 35281677,
 'GROSS_PROFIT': 11783455,
 'OPERATING_PROFIT': 12089992,
 'NET_INCOME': 11868109,
 'OPERATING_CASH_FLOW': 5761731}

In [201]:
asels_2021 = get_company_financials(
    ticker="ASELS",
    year=2021
)

asels_2021

{'TICKER': 'ASELS',
 'YEAR': 2021,
 'CASH': 2492096,
 'RECEIVABLES': 9803350,
 'INVENTORY': 7638954,
 'CURRENT_ASSETS': 23175142,
 'TOTAL_ASSETS': 46413298,
 'CURRENT_LIABILITIES': 16749927,
 'NONCURRENT_LIABILITIES': 3828161,
 'TOTAL_LIABILITIES': 20578088,
 'EQUITY': 25835210,
 'REVENUE': nan,
 'GROSS_PROFIT': nan,
 'OPERATING_PROFIT': nan,
 'NET_INCOME': nan,
 'OPERATING_CASH_FLOW': nan}

In [202]:
def find_financial_table(tables, search_text):

    candidates = []

    for i, table in enumerate(tables):

        table_text = (
            table
            .astype(str)
            .apply(lambda col: " ".join(col))
            .str.cat(sep=" ")
        )

        if search_text.lower() in table_text.lower():
            candidates.append((i, table.shape))

    return candidates

In [206]:
def find_main_table(tables, search_text):

    candidates = []

    for i, table in enumerate(tables):

        table_text = " ".join(
            table.astype(str).fillna("").values.flatten()
        )

        if search_text.lower() in table_text.lower():
            candidates.append(
                {
                    "index": i,
                    "rows": table.shape[0],
                    "cols": table.shape[1]
                }
            )

    if not candidates:
        return None

    candidates = sorted(
        candidates,
        key=lambda x: x["rows"],
        reverse=True
    )

    return candidates[0]

In [207]:
find_main_table(
    tables,
    "Kar veya Zarar ve Diğer Kapsamlı Gelir Tablosu"
)

{'index': 300, 'rows': 303, 'cols': 5}

In [208]:
find_main_table(
    tables,
    "Nakit Akış Tablosu"
)

{'index': 453, 'rows': 407, 'cols': 5}

In [209]:
income_statement = tables[300]

search_items = [
    "Hasılat",
    "TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR)",
    "ESAS FAALİYET KARI (ZARARI)",
    "DÖNEM KARI (ZARARI)"
]

for item in search_items:

    result = income_statement[
        income_statement[1]
        .astype(str)
        .str.strip()
        .eq(item)
    ]

    print("\n", item)
    print(result[[1, 3, 4]])

 Hasılat
         1           3           4
5  Hasılat  35.281.677  20.138.953

 TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR)
                                        1           3          4
9  TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR)  11.783.455  6.648.911

 ESAS FAALİYET KARI (ZARARI)
                              1           3          4
75  ESAS FAALİYET KARI (ZARARI)  12.089.992  9.418.168

 DÖNEM KARI (ZARARI)
                       1           3          4
117  DÖNEM KARI (ZARARI)  11.868.109  7.127.341

In [210]:
cash_flow_statement = tables[453]

item = "İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI"

result = cash_flow_statement[
    cash_flow_statement[1]
    .astype(str)
    .str.strip()
    .eq(item)
]

print(result[[1, 3, 4]])

                                         1          3          4
3  İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI  5.761.731  2.432.551

In [211]:
ticker = "ASELS"
year = 2021

oid = get_oid(ticker)

url = (
    f"https://www.kap.org.tr/tr/api/home-financial/"
    f"download-file/{oid}/{year}/T"
)

response = requests.get(url)
response.raise_for_status()

zip_file_2021 = io.BytesIO(response.content)

with zipfile.ZipFile(zip_file_2021, "r") as z:
    files_2021 = z.namelist()

files_2021

['ASELS_1006150_2021_4.xls',
 'Dönem4Ekler/(0)ASELSAN CMB Report 31.12.2021.pdf',
 'Dönem4Ekler/(1)ASELSAN SPK RAPORU 31.12.2021.pdf',
 'ASELS_972600_2021_3.xls',
 'Dönem3Ekler/(1)ASELSAN CMB Report 30.09.2021.pdf',
 'Dönem3Ekler/(2)ASELSAN SPK RAPORU 30.09.2021.pdf',
 'ASELS_957064_2021_2.xls',
 'Dönem2Ekler/(2)ASELSAN CMB Report 30.06.2021.pdf',
 'Dönem2Ekler/(3)ASELSAN SPK RAPORU 30.06.2021.pdf',
 'ASELS_931412_2021_1.xls',
 'Dönem1Ekler/(3)ASELSAN CMB Report 31.03.2021.pdf',
 'Dönem1Ekler/(4)ASELSAN SPK RAPORU 31.03.2021.pdf']

In [ ]:
find_financial_table(
    tables,
    "Nakit Akış Tablosu"
)

[(453, (407, 5)), (454, (1, 4))]

In [212]:
annual_file_2021 = [
    file for file in files_2021
    if file.endswith("_4.xls")
][0]

with zipfile.ZipFile(zip_file_2021, "r") as z:
    with z.open(annual_file_2021) as file:
        annual_data_2021 = file.read()

tables_2021 = pd.read_html(
    StringIO(
        annual_data_2021.decode("utf-8")
    )
)

print(len(tables_2021))

722

In [213]:
income_2021 = tables_2021[300]

display(
    income_2021.head(10)
)

                                                0   1   2   3
0  Kar veya Zarar ve Diğer Kapsamlı Gelir Tablosu NaN NaN NaN

In [214]:
find_main_table(
    tables_2021,
    "Kar veya Zarar ve Diğer Kapsamlı Gelir Tablosu"
)

{'index': 299, 'rows': 299, 'cols': 5}

In [215]:
find_main_table(
    tables_2021,
    "Nakit Akış Tablosu"
)

{'index': 450, 'rows': 407, 'cols': 5}

In [216]:
find_main_table(
    tables_2021,
    "Finansal Durum Tablosu"
)

{'index': 1, 'rows': 593, 'cols': 5}

In [217]:
def find_main_table(tables, search_text):

    candidates = []

    for i, table in enumerate(tables):

        table_text = " ".join(
            table.astype(str).fillna("").values.flatten()
        )

        if search_text.lower() in table_text.lower():
            candidates.append((i, table))

    if not candidates:
        raise ValueError(
            f"'{search_text}' içeren tablo bulunamadı."
        )

    # Nested küçük tablolar yerine en fazla satıra sahip ana tablo
    _, main_table = max(
        candidates,
        key=lambda x: x[1].shape[0]
    )

    return main_table

In [218]:
balance_sheet = find_main_table(
    tables,
    "Finansal Durum Tablosu"
)

income_statement = find_main_table(
    tables,
    "Kar veya Zarar ve Diğer Kapsamlı Gelir Tablosu"
)

cash_flow_statement = find_main_table(
    tables,
    "Nakit Akış Tablosu"
)

In [219]:
asels_2021 = get_company_financials(
    ticker="ASELS",
    year=2021
)

asels_2021

{'TICKER': 'ASELS',
 'YEAR': 2021,
 'CASH': 2492096,
 'RECEIVABLES': 9803350,
 'INVENTORY': 7638954,
 'CURRENT_ASSETS': 23175142,
 'TOTAL_ASSETS': 46413298,
 'CURRENT_LIABILITIES': 16749927,
 'NONCURRENT_LIABILITIES': 3828161,
 'TOTAL_LIABILITIES': 20578088,
 'EQUITY': 25835210,
 'REVENUE': nan,
 'GROSS_PROFIT': nan,
 'OPERATING_PROFIT': nan,
 'NET_INCOME': nan,
 'OPERATING_CASH_FLOW': nan}

In [258]:
import requests
import io
import zipfile
import time
import pandas as pd
import numpy as np

from io import StringIO
from pathlib import Path


# =========================================================
# 1. TICKER -> KAP OID
# =========================================================

def get_oid(ticker):

    url = f"https://www.kap.org.tr/tr/api/member/filter/{ticker}"

    response = requests.get(
        url,
        timeout=60
    )

    response.raise_for_status()

    data = response.json()

    if not data:
        return None

    return data[0]["mkkMemberOid"]


# =========================================================
# 2. FINANCIAL VALUE PARSER
# =========================================================

def parse_financial_value(value):

    if pd.isna(value):
        return np.nan

    # Pandas değeri zaten numeric okuduysa
    if isinstance(
        value,
        (int, float, np.integer, np.floating)
    ):
        return value

    value = str(value).strip()

    if value in ["", "-", "nan", "NaN"]:
        return np.nan

    # Örnek:
    # (1.250.000) -> -1250000

    if value.startswith("(") and value.endswith(")"):

        value = value[1:-1]
        value = value.replace(".", "")

        return -int(value)

    # Örnek:
    # 1.250.000 -> 1250000

    value = value.replace(".", "")

    return int(value)


# =========================================================
# 3. FİNANSAL TABLOYU İÇERİĞİNDEN BUL
# =========================================================

def find_main_table(tables, required_items):

    candidates = []

    for i, table in enumerate(tables):

        table_text = " ".join(
            table
            .astype(str)
            .fillna("")
            .values
            .flatten()
        ).lower()

        # Aradığımız finansal kalemlerin
        # tamamı bu tabloda var mı?

        if all(
            item.lower() in table_text
            for item in required_items
        ):

            candidates.append(
                {
                    "index": i,
                    "rows": table.shape[0],
                    "table": table
                }
            )

    if not candidates:

        raise ValueError(
            f"Gerekli kalemleri içeren tablo bulunamadı: "
            f"{required_items}"
        )

    # Nested küçük HTML tabloları yerine
    # en büyük tabloyu seç

    main_table = max(
        candidates,
        key=lambda x: x["rows"]
    )

    return main_table["table"]


# =========================================================
# 4. FİNANSAL KALEMİ TABLODAN AL
# =========================================================

def get_financial_item(df, item_name):

    mask = (
        df[1]
        .astype(str)
        .str.strip()
        .eq(item_name)
    )

    selected_row = df[mask]

    if selected_row.empty:
        return np.nan

    # Cari dönem
    value = selected_row[3].iloc[0]

    return value


# =========================================================
# 5. SUNUM PARA BİRİMİ / ÖLÇEK
# =========================================================

def get_unit_multiplier(tables):

    info_table = tables[0]

    mask = (
        info_table[0]
        .astype(str)
        .str.strip()
        .eq("Sunum Para Birimi")
    )

    if not mask.any():
        return 1, None

    presentation_currency = (
        info_table.loc[mask, 1]
        .iloc[0]
    )

    presentation_currency = str(
        presentation_currency
    ).strip()

    # Örnekler:
    #
    # TL            -> 1
    # 1 TL          -> 1
    # 1.000 TL      -> 1000
    # 1.000.000 TL  -> 1000000

    numeric_part = (
        presentation_currency
        .upper()
        .replace("TL", "")
        .strip()
    )

    if numeric_part == "":
        multiplier = 1

    else:

        numeric_part = (
            numeric_part
            .replace(".", "")
            .replace(",", "")
        )

        multiplier = int(numeric_part)

    return multiplier, presentation_currency


# =========================================================
# 6. YILLIK RAPORU KAP'TAN AL / CACHE'DEN OKU
# =========================================================

def get_annual_report_tables(
    ticker,
    year,
    cache_dir="kap_cache"
):

    cache_path = Path(cache_dir)

    cache_path.mkdir(
        parents=True,
        exist_ok=True
    )

    cache_file = (
        cache_path /
        f"{ticker}_{year}_annual.xls"
    )


    # -----------------------------------------------------
    # CACHE VARSA
    # -----------------------------------------------------

    if cache_file.exists():

        print(
            f"{ticker} - {year}: CACHE"
        )

        annual_data = cache_file.read_bytes()

        annual_file = cache_file.name


    # -----------------------------------------------------
    # CACHE YOKSA KAP
    # -----------------------------------------------------

    else:

        oid = get_oid(ticker)

        if oid is None:

            raise ValueError(
                f"{ticker} için KAP OID bulunamadı."
            )

        url = (
            "https://www.kap.org.tr/tr/api/home-financial/"
            f"download-file/{oid}/{year}/T"
        )

        response = requests.get(
            url,
            timeout=60
        )

        response.raise_for_status()

        zip_file = io.BytesIO(
            response.content
        )


        # ZIP kontrolü

        if not zipfile.is_zipfile(zip_file):

            raise ValueError(
                f"{ticker} - {year}: "
                "KAP'tan gelen dosya ZIP formatında değil."
            )


        # ZIP'i aç

        with zipfile.ZipFile(zip_file, "r") as z:

            files = z.namelist()

            annual_files = [
                file
                for file in files
                if file.endswith("_4.xls")
            ]

            if not annual_files:

                raise ValueError(
                    f"{ticker} - {year} için "
                    "yıllık finansal rapor bulunamadı."
                )

            if len(annual_files) > 1:

                print(
                    f"UYARI: {ticker} - {year} için "
                    f"{len(annual_files)} yıllık rapor bulundu."
                )

            annual_file = annual_files[0]

            with z.open(annual_file) as file:

                annual_data = file.read()


        # Cache'e kaydet

        cache_file.write_bytes(
            annual_data
        )

        print(
            f"{ticker} - {year}: KAP -> CACHE"
        )


    # -----------------------------------------------------
    # HTML TABLOLARINI OKU
    # -----------------------------------------------------

    tables = pd.read_html(
        StringIO(
            annual_data.decode("utf-8")
        )
    )

    return tables, annual_file


# =========================================================
# 7. TEK ŞİRKET - TEK YIL FİNANSALLARI
# =========================================================

def get_company_financials(ticker, year):

    # -----------------------------------------------------
    # RAPOR
    # -----------------------------------------------------

    tables, annual_file = get_annual_report_tables(
        ticker=ticker,
        year=year
    )


    # -----------------------------------------------------
    # SUNUM ÖLÇEĞİ
    # -----------------------------------------------------

    unit_multiplier, presentation_currency = (
        get_unit_multiplier(tables)
    )


    # -----------------------------------------------------
    # FİNANSAL TABLOLARI DİNAMİK BUL
    # -----------------------------------------------------

    balance_sheet = find_main_table(
        tables,
        [
            "TOPLAM VARLIKLAR",
            "TOPLAM ÖZKAYNAKLAR"
        ]
    )

    income_statement = find_main_table(
        tables,
        [
            "Hasılat",
            "DÖNEM KARI (ZARARI)"
        ]
    )

    cash_flow_statement = find_main_table(
        tables,
        [
            "İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI"
        ]
    )


    # -----------------------------------------------------
    # BİLANÇO KALEMLERİ
    # -----------------------------------------------------

    balance_items = {

        "CASH":
            "Nakit ve Nakit Benzerleri",

        "RECEIVABLES":
            "Ticari Alacaklar",

        "INVENTORY":
            "Stoklar",

        "CURRENT_ASSETS":
            "TOPLAM DÖNEN VARLIKLAR",

        "TOTAL_ASSETS":
            "TOPLAM VARLIKLAR",

        "CURRENT_LIABILITIES":
            "TOPLAM KISA VADELİ YÜKÜMLÜLÜKLER",

        "NONCURRENT_LIABILITIES":
            "TOPLAM UZUN VADELİ YÜKÜMLÜLÜKLER",

        "TOTAL_LIABILITIES":
            "TOPLAM YÜKÜMLÜLÜKLER",

        "EQUITY":
            "TOPLAM ÖZKAYNAKLAR"
    }


    # -----------------------------------------------------
    # GELİR TABLOSU
    # -----------------------------------------------------

    income_items = {

        "REVENUE":
            "Hasılat",

        "GROSS_PROFIT":
            "TİCARİ FAALİYETLERDEN BRÜT KAR (ZARAR)",

        "OPERATING_PROFIT":
            "ESAS FAALİYET KARI (ZARARI)",

        "NET_INCOME":
            "DÖNEM KARI (ZARARI)"
    }


    # -----------------------------------------------------
    # NAKİT AKIŞ
    # -----------------------------------------------------

    cash_flow_items = {

        "OPERATING_CASH_FLOW":
            "İŞLETME FAALİYETLERİNDEN NAKİT AKIŞLARI"
    }


    # -----------------------------------------------------
    # SONUÇ
    # -----------------------------------------------------

    financial_data = {

        "TICKER": ticker,

        "YEAR": year,

        "KAP_FILE": annual_file,

        "PRESENTATION_CURRENCY":
            presentation_currency,

        "UNIT_MULTIPLIER":
            unit_multiplier
    }


    # -----------------------------------------------------
    # HELPER
    # -----------------------------------------------------

    def add_financial_item(
        name,
        item_name,
        statement
    ):

        raw_value = get_financial_item(
            statement,
            item_name
        )

        parsed_value = parse_financial_value(
            raw_value
        )

        if pd.isna(parsed_value):

            financial_data[name] = np.nan

        else:

            # Bütün parasal değerleri TL'ye çevir

            financial_data[name] = (
                parsed_value *
                unit_multiplier
            )


    # -----------------------------------------------------
    # BİLANÇO
    # -----------------------------------------------------

    for name, item_name in balance_items.items():

        add_financial_item(
            name,
            item_name,
            balance_sheet
        )


    # -----------------------------------------------------
    # GELİR TABLOSU
    # -----------------------------------------------------

    for name, item_name in income_items.items():

        add_financial_item(
            name,
            item_name,
            income_statement
        )


    # -----------------------------------------------------
    # NAKİT AKIŞ
    # -----------------------------------------------------

    for name, item_name in cash_flow_items.items():

        add_financial_item(
            name,
            item_name,
            cash_flow_statement
        )


    return financial_data


# =========================================================
# 8. TEK ŞİRKET - TARİHSEL VERİ
# =========================================================

def get_company_history(
    ticker,
    start_year,
    end_year,
    request_delay=10,
    max_retries=5,
    cache_dir="kap_cache"
):

    results = []

    for year in range(
        start_year,
        end_year + 1
    ):

        cache_file = (
            Path(cache_dir) /
            f"{ticker}_{year}_annual.xls"
        )

        is_cached = cache_file.exists()


        # -------------------------------------------------
        # RETRY
        # -------------------------------------------------

        for attempt in range(max_retries):

            try:

                financial_data = (
                    get_company_financials(
                        ticker=ticker,
                        year=year
                    )
                )

                results.append(
                    financial_data
                )

                print(
                    f"{ticker} - {year}: OK"
                )


                # Cache'den gelmediyse bekle

                if not is_cached:

                    time.sleep(
                        request_delay
                    )

                break


            # -------------------------------------------------
            # HTTP ERROR
            # -------------------------------------------------

            except requests.exceptions.HTTPError as e:

                if (
                    e.response is not None
                    and
                    e.response.status_code == 429
                ):

                    wait_times = [
                        30,
                        60,
                        120,
                        180,
                        300
                    ]

                    wait_time = wait_times[
                        min(
                            attempt,
                            len(wait_times) - 1
                        )
                    ]

                    print(
                        f"{ticker} - {year}: "
                        f"RATE LIMIT -> "
                        f"{wait_time} sn bekleniyor..."
                    )

                    time.sleep(
                        wait_time
                    )

                else:

                    print(
                        f"{ticker} - {year}: "
                        f"ERROR -> {e}"
                    )

                    break


            # -------------------------------------------------
            # DİĞER ERROR
            # -------------------------------------------------

            except Exception as e:

                print(
                    f"{ticker} - {year}: "
                    f"ERROR -> {e}"
                )

                break


    # =====================================================
    # DATAFRAME
    # =====================================================

    df = pd.DataFrame(
        results
    )

    if not df.empty:

        df = (
            df
            .sort_values("YEAR")
            .reset_index(drop=True)
        )

    return df

def validate_financials(data):

    errors = []

    # Kontrol edilecek temel finansal kolonlar
    required_columns = [
        "CASH",
        "RECEIVABLES",
        "INVENTORY",
        "CURRENT_ASSETS",
        "TOTAL_ASSETS",
        "CURRENT_LIABILITIES",
        "NONCURRENT_LIABILITIES",
        "TOTAL_LIABILITIES",
        "EQUITY",
        "REVENUE",
        "GROSS_PROFIT",
        "OPERATING_PROFIT",
        "NET_INCOME",
        "OPERATING_CASH_FLOW"
    ]

    # 1. Missing kontrolü
    for col in required_columns:

        if col not in data or pd.isna(data[col]):
            errors.append(f"{col}_MISSING")


    # 2. Bilanço eşitliği
    if all(
        not pd.isna(data.get(col))
        for col in [
            "TOTAL_ASSETS",
            "TOTAL_LIABILITIES",
            "EQUITY"
        ]
    ):

        balance_difference = (
            data["TOTAL_ASSETS"]
            - (
                data["TOTAL_LIABILITIES"]
                + data["EQUITY"]
            )
        )

        # Yuvarlama farklarına tolerans
        tolerance = max(
            abs(data["TOTAL_ASSETS"]) * 0.001,
            1
        )

        if abs(balance_difference) > tolerance:

            errors.append(
                "BALANCE_SHEET_MISMATCH"
            )


    # 3. Dönen varlık > toplam varlık olamaz
    if (
        not pd.isna(data.get("CURRENT_ASSETS"))
        and
        not pd.isna(data.get("TOTAL_ASSETS"))
    ):

        if (
            data["CURRENT_ASSETS"]
            > data["TOTAL_ASSETS"]
        ):

            errors.append(
                "CURRENT_ASSETS_GT_TOTAL_ASSETS"
            )


    # 4. Kısa vadeli yükümlülük > toplam yükümlülük olamaz
    if (
        not pd.isna(data.get("CURRENT_LIABILITIES"))
        and
        not pd.isna(data.get("TOTAL_LIABILITIES"))
    ):

        if (
            data["CURRENT_LIABILITIES"]
            > data["TOTAL_LIABILITIES"]
        ):

            errors.append(
                "CURRENT_LIABILITIES_GT_TOTAL_LIABILITIES"
            )


    # 5. Sonuç
    is_valid = len(errors) == 0

    return {
        "TICKER": data.get("TICKER"),
        "YEAR": data.get("YEAR"),
        "IS_VALID": is_valid,
        "ERROR_COUNT": len(errors),
        "ERRORS": errors
    }

In [225]:
asels_2021 = get_company_financials(
    ticker="ASELS",
    year=2021
)

asels_2021

{'TICKER': 'ASELS',
 'YEAR': 2021,
 'KAP_FILE': 'ASELS_1006150_2021_4.xls',
 'CASH': 2492096,
 'RECEIVABLES': 9803350,
 'INVENTORY': 7638954,
 'CURRENT_ASSETS': 23175142,
 'TOTAL_ASSETS': 46413298,
 'CURRENT_LIABILITIES': 16749927,
 'NONCURRENT_LIABILITIES': 3828161,
 'TOTAL_LIABILITIES': 20578088,
 'EQUITY': 25835210,
 'REVENUE': 20138953,
 'GROSS_PROFIT': 6648911,
 'OPERATING_PROFIT': 9418168,
 'NET_INCOME': 7127341,
 'OPERATING_CASH_FLOW': 2432551}

In [226]:
asels_2022 = get_company_financials(
    ticker="ASELS",
    year=2022
)

asels_2022

{'TICKER': 'ASELS',
 'YEAR': 2022,
 'KAP_FILE': 'ASELS_1117839_2022_4.xls',
 'CASH': 5686996,
 'RECEIVABLES': 14888340,
 'INVENTORY': 12592653,
 'CURRENT_ASSETS': 38299445,
 'TOTAL_ASSETS': 76043841,
 'CURRENT_LIABILITIES': 29651397,
 'NONCURRENT_LIABILITIES': 6531475,
 'TOTAL_LIABILITIES': 36182872,
 'EQUITY': 39860969,
 'REVENUE': 35281677,
 'GROSS_PROFIT': 11783455,
 'OPERATING_PROFIT': 12089992,
 'NET_INCOME': 11868109,
 'OPERATING_CASH_FLOW': 5761731}

In [228]:
asels_history = get_company_history(
    ticker="ASELS",
    start_year=2016,
    end_year=2022
)

asels_history

ASELS - 2016: OK
ASELS - 2017: OK
ASELS - 2018: OK
ASELS - 2019: OK
ASELS - 2020: OK
ASELS - 2021: OK
ASELS - 2022: ERROR -> 429 Client Error: Request Limit Exceeded for url: https://www.kap.org.tr/tr/api/home-financial/download-file/4028e4a1413b7ef401413bc2251e0047/2022/T

,TICKER,YEAR,KAP_FILE,CASH,RECEIVABLES,INVENTORY,CURRENT_ASSETS,TOTAL_ASSETS,CURRENT_LIABILITIES,NONCURRENT_LIABILITIES,TOTAL_LIABILITIES,EQUITY,REVENUE,GROSS_PROFIT,OPERATING_PROFIT,NET_INCOME,OPERATING_CASH_FLOW
0,ASELS,2016,ASELS_587546_2016_4.xls,1168776,2039695,1187398,5069528,8604951,2242768,2670716,4913484,3691467,3768116,923018,810003,795201,980527
1,ASELS,2017,ASELS_661363_2017_4.xls,1262904,1601765,1944389,5798135,10918217,2671635,3198374,5870009,5048208,5360279,1354933,1173065,1387849,652285
2,ASELS,2018,ASELS_742448_2018_4.xls,3115691,3072113,3576618,11616680,19473631,4684478,4612132,9296610,10177021,9008516,2211092,2225096,2319347,-758732
3,ASELS,2019,ASELS_818469_2019_4.xls,3513842,3884933,4473927,13976498,25633043,7743870,4320274,12064144,13568899,13012551,3371733,3177262,3352673,850900
4,ASELS,2020,ASELS_911957_2020_4.xls,4081654,7146519,5532703,19594261,34094229,12319765,3676361,15996126,18098103,16104455,4605015,5276389,4461266,1718600
5,ASELS,2021,ASELS_1006150_2021_4.xls,2492096,9803350,7638954,23175142,46413298,16749927,3828161,20578088,25835210,20138953,6648911,9418168,7127341,2432551

In [230]:
asels_history = get_company_history(
    ticker="ASELS",
    start_year=2016,
    end_year=2022,
    sleep_seconds=3
)

asels_history

ASELS - 2016: OK
ASELS - 2017: OK
ASELS - 2018: OK
ASELS - 2019: OK
ASELS - 2020: OK
ASELS - 2021: OK
ASELS - 2022: OK

,TICKER,YEAR,KAP_FILE,CASH,RECEIVABLES,INVENTORY,CURRENT_ASSETS,TOTAL_ASSETS,CURRENT_LIABILITIES,NONCURRENT_LIABILITIES,TOTAL_LIABILITIES,EQUITY,REVENUE,GROSS_PROFIT,OPERATING_PROFIT,NET_INCOME,OPERATING_CASH_FLOW
0,ASELS,2016,ASELS_587546_2016_4.xls,1168776,2039695,1187398,5069528,8604951,2242768,2670716,4913484,3691467,3768116,923018,810003,795201,980527
1,ASELS,2017,ASELS_661363_2017_4.xls,1262904,1601765,1944389,5798135,10918217,2671635,3198374,5870009,5048208,5360279,1354933,1173065,1387849,652285
2,ASELS,2018,ASELS_742448_2018_4.xls,3115691,3072113,3576618,11616680,19473631,4684478,4612132,9296610,10177021,9008516,2211092,2225096,2319347,-758732
3,ASELS,2019,ASELS_818469_2019_4.xls,3513842,3884933,4473927,13976498,25633043,7743870,4320274,12064144,13568899,13012551,3371733,3177262,3352673,850900
4,ASELS,2020,ASELS_911957_2020_4.xls,4081654,7146519,5532703,19594261,34094229,12319765,3676361,15996126,18098103,16104455,4605015,5276389,4461266,1718600
5,ASELS,2021,ASELS_1006150_2021_4.xls,2492096,9803350,7638954,23175142,46413298,16749927,3828161,20578088,25835210,20138953,6648911,9418168,7127341,2432551
6,ASELS,2022,ASELS_1117839_2022_4.xls,5686996,14888340,12592653,38299445,76043841,29651397,6531475,36182872,39860969,35281677,11783455,12089992,11868109,5761731

In [231]:
from pathlib import Path

In [233]:
asels_history = get_company_history(
    ticker="ASELS",
    start_year=2016,
    end_year=2022,
    sleep_seconds=3
)

ASELS - 2016: KAP -> CACHE
ASELS - 2016: OK
ASELS - 2017: KAP -> CACHE
ASELS - 2017: OK
ASELS - 2018: KAP -> CACHE
ASELS - 2018: OK
ASELS - 2019: RATE LIMIT -> 3 sn bekleniyor...
ASELS - 2019: RATE LIMIT -> 6 sn bekleniyor...
ASELS - 2019: RATE LIMIT -> 9 sn bekleniyor...
ASELS - 2020: RATE LIMIT -> 3 sn bekleniyor...
ASELS - 2020: RATE LIMIT -> 6 sn bekleniyor...
ASELS - 2020: RATE LIMIT -> 9 sn bekleniyor...
ASELS - 2021: RATE LIMIT -> 3 sn bekleniyor...
ASELS - 2021: RATE LIMIT -> 6 sn bekleniyor...
ASELS - 2021: RATE LIMIT -> 9 sn bekleniyor...
ASELS - 2022: KAP -> CACHE
ASELS - 2022: OK

In [234]:
asels_history = get_company_history(
    ticker="ASELS",
    start_year=2016,
    end_year=2022,
    sleep_seconds=3
)

ASELS - 2016: CACHE
ASELS - 2016: OK
ASELS - 2017: CACHE
ASELS - 2017: OK
ASELS - 2018: CACHE
ASELS - 2018: OK
ASELS - 2019: KAP -> CACHE
ASELS - 2019: OK
ASELS - 2020: KAP -> CACHE
ASELS - 2020: OK
ASELS - 2021: KAP -> CACHE
ASELS - 2021: OK
ASELS - 2022: CACHE
ASELS - 2022: OK

In [236]:
asels_history = get_company_history(
    ticker="ASELS",
    start_year=2016,
    end_year=2022
)

ASELS - 2016: CACHE
ASELS - 2016: OK
ASELS - 2017: CACHE
ASELS - 2017: OK
ASELS - 2018: CACHE
ASELS - 2018: OK
ASELS - 2019: CACHE
ASELS - 2019: OK
ASELS - 2020: CACHE
ASELS - 2020: OK
ASELS - 2021: CACHE
ASELS - 2021: OK
ASELS - 2022: CACHE
ASELS - 2022: OK

In [238]:
tables_tuprs, _ = get_annual_report_tables(
    ticker="TUPRS",
    year=2019
)

print(len(tables_tuprs))

TUPRS - 2019: CACHE
726

In [239]:
for i, table in enumerate(tables_tuprs):

    table_text = " ".join(
        table.astype(str)
        .fillna("")
        .values
        .flatten()
    )

    if "Hasılat" in table_text:

        print(
            "INDEX:",
            i,
            "SHAPE:",
            table.shape
        )

INDEX: 299 SHAPE: (142, 6)
INDEX: 302 SHAPE: (1, 4)
INDEX: 305 SHAPE: (1, 4)

In [240]:
display(
    tables_tuprs[142].head(15)
)

                                  0   1   2   3
0  İhraç Edilmiş Borçlanma Araçları NaN NaN NaN

In [252]:
test_tickers = [
    "THYAO",
    "TUPRS",
    "EREGL",
    "BIMAS"
]

results = []

for ticker in test_tickers:

    try:

        data = get_company_financials(
            ticker=ticker,
            year=2019
        )

        results.append(data)

        print(f"{ticker}: OK")

    except Exception as e:

        print(f"{ticker}: ERROR -> {e}")

test_df = pd.DataFrame(results)

THYAO - 2019: CACHE
THYAO: OK
TUPRS - 2019: CACHE
TUPRS: OK
EREGL - 2019: KAP -> CACHE
EREGL: OK
BIMAS - 2019: KAP -> CACHE
BIMAS: OK

In [253]:
test_df

,TICKER,YEAR,KAP_FILE,CASH,RECEIVABLES,INVENTORY,CURRENT_ASSETS,TOTAL_ASSETS,CURRENT_LIABILITIES,NONCURRENT_LIABILITIES,TOTAL_LIABILITIES,EQUITY,REVENUE,GROSS_PROFIT,OPERATING_PROFIT,NET_INCOME,OPERATING_CASH_FLOW
0,THYAO,2019,THYAO_2019_annual.xls,12328,3205,1723,28339,146871,35417,70659,106076,40795,75118,13079,5042,4536,13029
1,TUPRS,2019,TUPRS_2019_annual.xls,10652009,4787906,9468581,27918955,55511558,28120266,14254752,42375018,13136540,89600776,4884287,2230137,585330,11334588
2,EREGL,2019,EREGL_818457_2019_4.xls,10590024,3344177,9329163,24136704,46672625,9450454,5974696,15425150,31247475,27465185,5011160,4378290,3494207,7243107
3,BIMAS,2019,BIMAS_824413_2019_4.xls,1158847,1433320,2368527,6127540,15173565,7319404,3616871,10936275,4237290,40211942,6985458,2122063,1224877,3384491

In [254]:
tables_thyao, _ = get_annual_report_tables(
    ticker="THYAO",
    year=2019
)

display(tables_thyao[0])

THYAO - 2019: CACHE

                         0             1
0        Sunum Para Birimi  1.000.000 TL
1  Finansal Tablo Niteliği     Konsolide

In [255]:
tables_eregl, _ = get_annual_report_tables(
    ticker="EREGL",
    year=2019
)

display(tables_eregl[0])

EREGL - 2019: CACHE

                         0          1
0        Sunum Para Birimi   1.000 TL
1  Finansal Tablo Niteliği  Konsolide

In [257]:
thyao_2019 = get_company_financials(
    "THYAO",
    2019
)

eregl_2019 = get_company_financials(
    "EREGL",
    2019
)

thyao_2019, eregl_2019

THYAO - 2019: CACHE
EREGL - 2019: CACHE

({'TICKER': 'THYAO',
  'YEAR': 2019,
  'KAP_FILE': 'THYAO_2019_annual.xls',
  'PRESENTATION_CURRENCY': '1.000.000 TL',
  'UNIT_MULTIPLIER': 1000000,
  'CASH': 12328000000,
  'RECEIVABLES': 3205000000,
  'INVENTORY': 1723000000,
  'CURRENT_ASSETS': 28339000000,
  'TOTAL_ASSETS': 146871000000,
  'CURRENT_LIABILITIES': 35417000000,
  'NONCURRENT_LIABILITIES': 70659000000,
  'TOTAL_LIABILITIES': 106076000000,
  'EQUITY': 40795000000,
  'REVENUE': 75118000000,
  'GROSS_PROFIT': 13079000000,
  'OPERATING_PROFIT': 5042000000,
  'NET_INCOME': 4536000000,
  'OPERATING_CASH_FLOW': 13029000000},
 {'TICKER': 'EREGL',
  'YEAR': 2019,
  'KAP_FILE': 'EREGL_2019_annual.xls',
  'PRESENTATION_CURRENCY': '1.000 TL',
  'UNIT_MULTIPLIER': 1000,
  'CASH': 10590024000,
  'RECEIVABLES': 3344177000,
  'INVENTORY': 9329163000,
  'CURRENT_ASSETS': 24136704000,
  'TOTAL_ASSETS': 46672625000,
  'CURRENT_LIABILITIES': 9450454000,
  'NONCURRENT_LIABILITIES': 5974696000,
  'TOTAL_LIABILITIES': 15425150000,
  'EQUITY': 31247475000,
  'REVENUE': 27465185000,
  'GROSS_PROFIT': 5011160000,
  'OPERATING_PROFIT': 4378290000,
  'NET_INCOME': 3494207000,
  'OPERATING_CASH_FLOW': 7243107000})

In [259]:
thyao_validation = validate_financials(
    thyao_2019
)

eregl_validation = validate_financials(
    eregl_2019
)

thyao_validation, eregl_validation

({'TICKER': 'THYAO',
  'YEAR': 2019,
  'IS_VALID': True,
  'ERROR_COUNT': 0,
  'ERRORS': []},
 {'TICKER': 'EREGL',
  'YEAR': 2019,
  'IS_VALID': True,
  'ERROR_COUNT': 0,
  'ERRORS': []})